
  const words = [
    { word: "Abay", meaning: "at. Qorǵanısh, saqlıq, es, abay-siyasat.", experience: "Sen bilmeysen meniń jayım, Onıń menen teń qudayım, Kerek emes bos abayıń, Tek tur, dedi Aydos baba (Berdaq)." },
    { word: "Abaylamay", meaning: "r. Sezbey, serlemey, bilmey.", experience: "Oksananıń qaysı esikke kirip ketkenin abaylamay da qaldım (M.Nızanov)." },
    { word: "Abzal", meaning: "r.Jaqsı, durıs, táwir.", experience: "Bul kúyikten frontqa ketkenim abzal ǵoy (K.Sultanov)."},
    { word: "Abısın", meaning: "at.Eki aǵayin jigittiń úlkeniniń kelinshegi kishkenesiniń kelinshegine abısın boladı.", experience: "Biziń abısın gáptiń posgellesin aytadı (K.Sultanov)." },
    { word: "Abadan", meaning: "kel. Jetkilikli, mol, kóp, qurǵın, barshılıq.", experience: "Xalıq shaǵlap mustaqıl Ózbekstanda, Dúnya tınısh, eller abadan bolsın (I. Yusupov). Ádira qalǵır tuwǵan jer, Bolmaǵan soń abadan (Jiyen jıraw)."},
    { word: "Abay-siyasat", meaning: "at. Kózabaǵa qır kórsetiwshilik.", experience: "Shopanlarǵa kelip, abay-siyasat qılıp, túsingenlerine násiyat aytıp, xannan kelgen jasawıl ne dep turıptı (Ó.Xojaniyazov)."},
    { word: "Abat", meaning: "kel. Barshılıq, molshılıq, toqshılıq, qurǵınlıq, qurǵınlılıq, juqnalılıq, jetkiliklilik, mol, bar, aǵıl-tegil, esap-sansız, tawsılmaytuǵın.", experience: "Jiyenge haq názer saldı, Mal dúnyası abat boldı (Berdaq). Eki dúnyası birdey abat bolsın jigittiń! (T. Qayıpbergenov)."},
    { word: "Abaysız", meaning: "Ańlamastan, bayqawsız, bayqamastan, dıqqatsız, sersiz, ańsız, bilmesten, ǵapılda.", experience: "Sonda abaysız kelip demde, birew kózin bastı áste (I.Yusupov)."},
    { word: "Abajur", meaning: "Kúshli jaqtılıq kózdi qamastırmawı hám tiyisli orınǵa ǵana toplanıp túsiwi ushın lampanıń ústine ornatılǵan (gezleme, qaǵaz t. b. nárselerden jasalǵan) qaplama, shıra.", experience: ""},
    { word: "Abaq", meaning: "Jılımnıń etegi, sheti, jiyegi.", experience: "Ara-tura salǵan jılım, abaǵım, maylaǵanda úyip keler qabaǵın (S.Nurımbetov)."},
    { word: "Abıray", meaning: "Ataq, dańq, mártebe.", experience: "Kolxozshılar arasında, rayon aldında iskerlik kútá abıray (Q.Dosanov)."},
    { word: "Abonent", meaning: "Abonementke iye bolǵan adam, abonementi bar kisi. Telefonnıń abonenti."},
    { word: "Abort", meaning: "Balanı waqtınan burın operaciya jolı menen alıp taslaw usılı, boydan túsiriw jolı."},
    { word: "Absolyut", meaning: "Idealistlik filosofiya túsiniginde álemniń máńgilik ózgermeytuǵın dáslepki negizi (ruwx, sana)."},
    { word: "Abır-sabır", meaning: "Ala topalań, apır-tapır, patırat, ersili-qarsılı, tártipsiz."},
    { word: "Abbazı", meaning: "at. Burınǵı Xiywa xanlıǵınıń tusındaǵı pul birligi.", experience: "Bárshesi eki abbazı. Bayǵa bolmas kóbi-azı, Bolsın biyshara razı, Haqısın bergil shermende (Ótesh shayır)."},
    { word: "Abbreviatura", meaning: "at. Sózlerdiń jazıwdaǵı shártli túrde qısqartılıwı, sonday-aq, eki yamasa bir neshe sózlerden qısqartılıp alınǵan sóz.", experience: "QMU, AQSh, BMSh, MPJ, TashMAU."},
    { word: "Abiturient", meaning: "at. Joqarı oqıw ornına kiriwshi, hújjetin endi ǵana tapsırǵan oqıwshı."},
    { word: "Abonement", meaning: "at. Bir nárseden paydalanıw ushın alınǵan hújjet, kelisim boyınsha bir nárseni shártli waqıt ishinde tiyisli bahası menen paydalanıw huqıqı.", experience: "Teatr abonementi. Avtobus abonementi."},
    { word: "Abstrakciya", meaning: "at. Zattıń belgisine, qásiyetine qaramastan oylap shıǵarıw."},
    { word: "Abızámzám", meaning: "at. Zámzám suwı musılmanlardıń teberik dep esaplaytuǵın Káábanıń janındaǵı qudıqtıń suwı.", experience: "Abızámzám yańlı shiyrin suwıń bar. Watan jerin abat etken dáryasań. (S.Nurımbetov). Abızámzámniń suwınday birewlerdiń taza muhabbatın urladıń sen náletiy urıs (Ó.Xojaniyazov)."},
    { word: "Abılaysań", meaning: "at. 1. Parsısha abináysan náysan (aprel) ayında jawǵan jawın, báhár jawını, nóser. 2. Mif. Qazaq, qaraqalpaq xalıqlarında gezlesetuǵın ańızlarda dúzde ólgen Abılaysań batırdıń denesin juwıw ushın jawǵan jawın. 3. Sel bolıp aqqan kóz jası.", experience: "Abılaysań jamǵırday. Kóziniń jası móltildep, Etegine quyadı (A.Dabılov)."},
    { word: "Abınıw", meaning: "f. Qaptırılıw, súriniw, kepleniw, taplanıw, et betinen túsiw.", experience: "Múshirip qaqań etip, erdiń ústinen sekirip, attıń jalına abınıp ketti (K.Sultanov), Qalǵanlarımız oshaqqa abınıp, mollamdógerek bolıp otırmız (K.Sultanov)."},
    { word: "Abırjı", meaning: "kel. Muzdıń hálsiregen waqtı, qolaysız, hálsiz, qáwipli.", experience: "Muz hálsirep, jol abırjı bolǵannan berli úyine kelgendi de qoydı (A.Begimov). Muz bir qatıp bekkemlespey turıp, jıllı bolıp ketse, abırjı bolıp ústinen adam júre almaydı (Q.Irmanov)."},
    { word: "Avangard", meaning: "at. Aldınǵı, bastaǵı, birinshi, jol kórsetkish, úlgi kórsetiwshi, atlanıs jasaǵanda áskerlerdiń eń aldıńǵı tobı.", experience: "Ózi issheń basqalarǵa avangard (Á.Shamuratov)."},
    { word: "Avantyura", meaning: "at. Hádiyse, hiylekerlik, hiylekerlik siyasat, hádiyselerge túsiw, hár qıylı jollarǵa túsiw.", experience: "Áskeriy avantyura, siyasiy avantyura."},
    { word: "Avariya", meaning: "at. 1. Mashina mexanizminiń bir jeriniń buzılıwı, buzılıw, qıyralıw, sátsizlik. 2. Baxıtsız hádiyse, apat, qáwip.", experience: "Avariyaǵa ushıraw. Mashinanı avariyasız aydaw."},
    { word: "Aviamodel", meaning: "at. Ushıwshı apparattıń modeli."},
    { word: "Aviapochta", meaning: "at. Pochtanı hawa jolı menen jetkeriw, amanattıń hawa jolı arqalı jiberiliwi."},
    { word: "Aviator", meaning: "at. Lyotchik, ushqısh, ushıwshı, ushıw menen shuǵıllanıwshı, hawa-jol qatnasında islewshi."},
    { word: "Aviaciya", meaning: "at. Hawada júriw quralı, hawadaǵı ushıwdıń háreket etiw usılı.", experience: "Úlken qısqı palatkaǵa da jańa aviaciya mektebin pitkergen jas lyotchikler hám shturmanlar jıynalǵan edi  (N.Dáwqaraev)."},
    { word: "Avtobaza", meaning: "at. Avtomobiller saqlanatuǵın, buyırtpa boyınsha jumsawǵa mashinalardı beretuǵın transport mákemesi."},
    { word: "Avtobiografiya", meaning: "at. Ómirbayan, óz ómirbayanı.", experience: "Uǵıljannıń jalǵız atınan basqa hesh bir avtobiografiyasına tiyisli maǵlıwmatınıń bolmaǵanı izlewdi biraz qıyınlastırıwı múmkin (A.Bekimbetov)."},
    { word: "Avtobus", meaning: "at. Adamlardı tasıytuǵın kóp orınlı avtomobil.", experience: "Uzaq joldı qısqartıp, avtobusqa jeńgizgen (T.Seytmamutov). Tramvayı, avtobusı dóngelep, dóngelek tur bir-birine minbelep (M.Dáribaev)."},
    { word: "Avtograf", meaning: "at. Avtordıń óz qolı menen jazılǵan qoltańbası, óziniń qoyǵan qolı.", experience: "Shirkew diywallarında ótken ásirlerde jazılǵan rus soldatlarınıń tolıp atırǵan avtograf jazıwları bar (Q.Ayımbetov)."},
    { word: "Avtozavod", meaning: "at. Avtomobil zavodı, avtomobiller soǵılatuǵın zavod, avtomobil islep shıǵaratuǵın jer, orın."},
    { word: "Avtokolonna", meaning: "at. Alıs jolǵa shıqqanda birge júretuǵın mashinalar toparı.", experience: "Úshinshi kúni túnde front liniyasına dushpannıń avtokolonnası jaqınlap kiyatır degen xabar aldıq (N.Dáwqaraev)."},
    { word: "Avtol", meaning: "at. Avtomashina, avtomobil traktorlardı háreketke keltiretuǵın, qurılısların maylaytuǵın maydın túri, mashina mayı."},
    { word: "Avtolavka", meaning: "at. Kóshpeli dúkán, avtomashinanıń ishine jayǵastırılǵan, qálegen jerge barıp sawda isley beretuǵın dúkán.", experience: "Inim usındayıń bar da, avtolavka bekitse men de isleymen (Q.Jumaniyazov)."},
    { word: "Avtomat", meaning: "at. Ishki mexanizmlerdiń kúshi menen ózinen-ózi jumıs apara alatuǵın qural, ózinshe isleytuǵın apparat, ásbap.", experience: "Telefon-avtomat."},
    { word: "Avtomashina", meaning: "at. Avtomobil, avtobus, júk tasıytuǵın yamasa jeńil mashina.", experience: "GAZ-69 markalı jeńil avtomashina alǵa qaray zuwlap ketti (A.Bekimbetov). Dushpannıń 15 samolyotı, 5 tank, 14 avtomashinası joq etildi (T.Qayıpbergenov)."},
    { word: "Avtonomiya", meaning: "at. Belgili bir xalıqtıń ózin ózi basqarıw huqıqı, milliy huqıqı."},
    { word: "Avtoportret", meaning: "at. Xudojniktiń ózi tárepinen islengen óziniń (portreti) súwreti."},
    { word: "Avtor", meaning: "at. Ilimiy hám ádebiy shıǵarmalardıń hám t. b. miynetlerdiń iyesi, dóretiwshisi.", experience: "Baspasóz basqarması bolmay tabı, Otırdı buyrıq jazıp avtorlarǵa (I. Yusupov)."},
    { word: "Avtoreferat", meaning: "at. Qanday da bir ilimiy izertlewdiń avtor tárepinen eń qısqa etip jazılǵan túri."},
    { word: "Abzac", meaning: "at. Tekst basındaǵı yáki onıń ayırım pikir bildirilgen bólegindegi birinshi sózdiń birinshi háribin jazıwda ońǵa qaray jasalǵan sál sheginis, taza joldan baslanǵan jazıw, bir taza joldan ekinshi taza jolǵa shekemgi aralıq, jazıwdaǵı eń dáslepki jol.", experience: "Abzactan jazıw."},
    { word: "Avtoruchka", meaning: "at. Sıyası peroǵa óz-ózinen quyılıp turatuǵın ruchka."},
    { word: "Agent", meaning: "at. Basqa bir eldiń jasırın tapsırması menen kelgen adam, wákil, elshi, jasırın tıńshı.", experience: "Anglichan imperialistleriniń agentleri bolǵan túrkmen feodalları Bozatawdı jawızlıq penen shaptı (B.Ismaylov)."},
    { word: "Agentura", meaning: "at. Jasırın maǵlıwmatlar jıynaw ushın shólkemlestirilgen elshilik xızmet."},
    { word: "Agitator", meaning: "at. Kópshilik arasında úgit-násiyat jumısın júrgiziwshi adam.", experience: "Usı brigadada basqalar menen jumıs islep agitatorlıqtı da alıp baratuǵın Atamurat. Áne, agitator kiyatır eken, dedi sonıń arasında bir kolxozshı (T.Qayıpbergenov)."},
    { word: "Agitpunkt", meaning: "at. Úgit-násiyat isi menen shuǵıllanatuǵın jer, adamlar arasında siyasiy massalıq jumısın júrgizetuǵın jergilikli mákeme."},
    { word: "Agrarlıq", meaning: "kel. Jerdi paydalanıwǵa hám iyelewge tiyisli.", experience: "Agrarlıq reforma. Agrarlıq másele."},
    { word: "Agregat", meaning: "at. Bir neshe túrdegi mashinalardıń birikpesi, quramalı mashinalarda hár túrli detallardıń birikpesi, hár túrli tiptegi bir yamasa bir neshe mashinalardıń birigip ulıwmalıq iske qosılıwı.",},
    { word: "Agressor", meaning: "at. Basıp alıwshı, basqınshı."},
    { word: "Agronom", meaning: "at. Agronomiya boyınsha qánige, maman, awıl xojalıq isleri boyınsha qánigelikti iyelegen kisi.", experience: "Áliy aǵa bir neshe jıllardan berli «Kegeyli» sovxozınıń bir uchastkasında agronom bolıp isleydi (Ó.Xojaniyazov)."},
    { word: "Agronomiya", meaning: "at. Jerdi islew hám awıl xojalıǵı haqqında ilim.", experience: "Agronomiyalıq laboratoriyalar dúzildi (O.Berdimuratov)."},
    { word: "Agrotexnika", meaning: "at. Awıl xojalıq eginlerin islewdiń sisteması, diyqanshılıq hám olardı rawajlandırıw sharaları, ilajları.", experience: "Barlıq agrotexnika jetiskenliklerin keńnen qollanıw zárúr (O.Berdimuratov)."},
    { word: "Agroximiya", meaning: "at. Ósimliklerdi azıqlandırıw, olardı (jaqsı jaǵdayda) rawajlandırıw tuwralı ilim, ósimliklerdi túrli zıyanlı nárselerden qorǵaw hám t. b. ilajlar kóriw usılı.",},
    { word: "Aǵa-jeńge", meaning: "at. Ózinen úlken aǵası hám onıń hayalı, jası úlken, jası kishi tuwısqanları.", experience: "Qosıbay tubalap, tolǵanıp, aqırı shapandı sandıqtıń tórine tasladı da, bas elshi ózi bolıp, aǵa-jeńgesiniń alıp keldi riyzalıǵın (K.Sultanov)." },
    { word: "Aǵa-ini", meaning: "Tuwısqanlıq qatnastaǵı ul perzentler.", experience: "Dos-yaran, jaqın qatnastaǵı adamlar. Onıń arqa súyeri, tuwısqan-tuwǵanları, pútkil kollektivi, (Ó.Ayjanov)."},
    { word: "Aǵalıq", meaning: "Jası úlkenlik, ǵamxorlıq, jol basshılıq, qáwenderlik.", experience: "Jigit boldım kem-kem keldi aǵalıq (T.Jumamuratov)."},
    { word: "Aǵarbulaq", meaning: "Molshılıq, asıp-tasıwshılıq, tawsılmaytuǵın", experience: "Fermamız aǵarbulaq may boladı (K.Sultanov)."},
    { word: "Aǵarǵan", meaning: "Qatıq, sút, ayran", experience: "Qara qoydıń terisi sabınlap juwsań aǵarmas (Q.Ayımbetov)."},
    { word: "Aǵa-apa", meaning: "at. Áke-sheshe, tuwǵan-tuwısqan, úlken-kishi.", experience: "Kúndizinde aǵa-apalarımız atızlarda isleydi (A.Bekimbetov)."},
    { word: "Aǵa-begler", meaning: "at. Jası úlken, jası kishiler, húrmetli otaǵasılar, xalayıqlar, el-jurtlar, jası úlken, jası kishi.", experience: "Áne aǵa-begler, endigi gáp sizlerden yar-doslar. (Q.Aralbaev)."},
    { word: "Aǵabek", meaning: "at. 1. Basqarıwshı, shólkemlestiriwshi, basshılıq etiwshi kisi. 2.Menshikli at, isim."},
    { word: "Aǵabiy", meaning: "at. Hámel, biylik", experience: "Xalıqtıń úrp-ádetinen qalıp ketken «aǵabiy» oyınları oynaldı (Q.Ayımbetov)."},
    { word: "Aǵay", meaning: "at. Ózinen jası úlken kisi, atın bilmegen jası úlkenge xabarlasıw ushın qollanılatuǵın qaratpa sóz, sıpayılıq mánisinde jası úlkenge múrájat.", experience: "Allambergen aǵay abıraylı xojalıqqa aylandı (J.Aymurzaev)."},
    { word: "Aǵayin", meaning: "at. Tuwǵan-tuwısqan, urıwlas, ata-babaları tuwısqan adamlar.", experience: "Aǵayiniń kóp bolsa adam tiymes, kósewin uzın bolsa qolın kúymes (qq.x.n.) Sebebi Esengeldi menen Qosıbay ar-namısı sherik aǵayin edi (K.Sultanov)."},
    { word: "Aǵarańlaw", meaning: "f. Bir nárseniń shala-sharpı kóriniwi, uzaqtan bozarańlap kózge túsiwi, bozarıp kóriniw, eleslew.", experience: "Kún nurına shaǵılısıp, qarday aǵarańlaydı (Aybek). Aǵarańlap tań atıp kiyatır (Ó.Xojaniyazov)."},
    { word: "Aǵarmay", meaning: "at. Aǵartılǵan may, aq may, paxta mayı."},
    { word: "Aǵartıw I.", meaning: "f. Aq etiw, háklew, tazalaw, juwıw.", experience: "Íssı quyash aǵartıp jibergen qalpaǵın shaqqan kiyip shıǵıp ketti (K.Smamutov)."},
    { word: "Aǵartıw II.", meaning: "f. Sawatlandırıw, túsindiriw, oqıtıw, sawatın ashıw, bilimlendiriw.", experience: "Xalıq bárhama ádiwleydi senińdey, Aǵartıwdıń tuńǵısh qarlıǵashların (I. Yusupov). Shayır sózi menen oqıtıwshınıń kewlin, kózqarasın aǵartadı (G.Esemuratov)."},
    { word: "Aǵartıwshı", meaning: "at. 1. Aq etiwshi, háklewshi, tazalawshı. 2. Aǵartıw jumısın júrgiziwshi, xalıq arasında úgit-násiyat aparıwshı, sawatlandırıw isi menen shuǵıllanıwshı."},
    { word: "Aǵawız", meaning: "kel. Pispegen, shala, waqtı jetpegen, shiyki, waqtı tolmaǵan.", experience: "Sen qaraqalpaq, qazaq bolǵanda, Ketpenlep egin ekkende, Ketpenlep ekken eginiń, Ortada aǵawız qalǵanda (Kunxoja)."},
    { word: "Aǵash", meaning: "at. Terek, ádette, terektiń úlkeygeni, quwraǵı, qurılıs hám xojalıq islerinde paydalanılatuǵın shiyki zattıń túrine aytıladı.", experience: "Qonıp ǵarǵaday aǵashqa, Dúnyanıń máwsimin kórdim (Ótesh shayır). Aǵash ergenektiń ekewi de tabaldırıqqa shekem naǵısqa sırǵıp tur (K.Sultanov). Oń qaptalda aǵash kát (N.Dáwqaraev)."},
    { word: "Aǵza", meaning: "at. 1. Múshe. 2. Qanday da bir topar, aymaq hám t. b. jasawshı, oǵan tiyisli adam. 3. Qanday da bir mákeme, shólkem, jıyın aǵzası.",experience: "1.Adam yamasa haywan aǵzası. 2.Shańaraq aǵzası."},
    { word: "Aǵla", meaning: "kel. Jaqsı, artıqmash, ayrıqsha, artıq, ziyada, zıyat.", experience: "Súysen miyriń qanıp ol intizarıń, Bul dúnya beyishten aǵla kórindi (Berdaq). Bul aqılıń bárinen de aǵla bolǵan eken (Q.Ayımbetov)."},
    { word: "Aǵızıw", meaning: "f. Suyıqlıqtı shıǵarıw, tógiw,", experience: "Ǵayrı birewlerdi etip qurdasıń, júrme aǵızıp dilbarıńnıń kóz jasın (Berdaq). Janǵa jaylı aǵızadı til mayın, Qızıq sózdi túsiniwge dım qayım (I. Yusupov)."},
    { word: "Aǵılıw. I", meaning: "f. 1. Izi úzilmew, tógiliw, molayıw. 2. Shubırıw, ıǵılıw.", experience: "Kelgen kúnniń ózinde-aq ol áynek aldında otırıp, kóshede úzliksiz aǵılıp baratırǵan adamlarǵa qızıǵıp qaraytuǵın edi (R.Tagor)."},
    { word: "Aǵılıw II", meaning: "f. Ótip turıw, júrip turıw.", experience: "Baǵdarı bar gúl japıraǵın jamılǵan, sımlar boylap aǵılǵan (I. Qurbanbaev)."},
    { word: "Aǵım", meaning: "at. Baǵıt, baǵdar, ıńǵay, tárep, taman."},
    { word: "Arıs", meaning: "at. Suyıqlıqtaǵı háreket, qıymıl, suw aǵısı.", experience: "Úshewi taǵı da qosılıp, tómen qaray aǵıs penen aqırın aǵıp baratır (J.Aymurzaev)."},
    { word: "Aǵıw", meaning: "f. 1. Tógiliw, quyılıw, ıǵılıw, ıǵıw. 2. Suwdıń belgili baǵdardaǵı, háreketi, qıymılı.", experience: "Aqdáryadan suw aǵadı salmaǵa, Yar kiyatır salmadan suw almaǵa (qq.x.q.)."},
    { word: "Aǵıw-qarası", meaning: "at. Dúnyaǵa shıǵıp kórgeni, barı, birgenesi, jalǵızı.", experience: "Jaman dep aytsań da baydıń balasın, birewdiń kóziniń aǵıw-qarası (Omar)."},
    { word: "Ada bolıw", meaning: "f. Tawsılıw, tamam bolıw, sap bolıw, joq bolıw.", experience: "Bar ómirim boldı ada, Óttiń be qurǵan ómirim (Berdaq). Ada bolmas ayta berseń, zarlı ómirdi etseń dástan (Á.Shamuratov)."},
    { word: "Adaq arba", meaning: "at. Ayaq arba (balalardı júriwge úyretetuǵın aǵashtan islengen buyım).", experience: "Seniń balańa adaq arba soǵaman (T.Qayıpbergenov)."},
    { word: "Adalaw", meaning: "f. Tamamlaw, tawısıw, túwesiw, joq etiw.", experience: "Táwekel etip allańa, Shubar atıńdı tapsırdıń. Aytar sózińdi adalap («Alpamıs»)."},
    { word: "Adam ata", meaning: "at. Adam álayhissalam. Diniy isenim boyınsha Alla tárepinen jaratılǵan jer júzindegi eń birinshi adam hám adamzattıń atası.", experience: "Adam ata menen Hawa eneni (Áweneni) topıraqtan bina etedi (K.Sultanov)."},
    { word: "Adamgershilik ", meaning: "at. Múnásibetlilik, siz-bizlik, óz-ara sıylasıq, dos-yaranlıq, sanalılıq, kórgenlilik, hújdanlılıq.", experience: "Sırtqı pishińnen naǵız adamgershilikli júrek soǵıp turǵanlıǵın biliw qıyınǵa túspedi (I. Yusupov)."},
    { word: "Adamzat", meaning: "at. Barlıq adam balası, pútkil adam, qanday adam bolmasın barlıǵı.", experience: "Tawdı, tastı jel buzar, adamzattı sóz buzar (qq.x.n.). Adamzat hám eki túrli. Biri batır, biri qorqaq. Batırman dep kóp maqtansa, Sol adamnıń ózi qorqaq (S.Májitov)."},
    { word: "Adamxor", meaning: "kel. Adam qumar, asaw, jabayı, adam óltiretuǵın, qáwipli, jırtqısh, qutırǵan.", experience: "Adamxorday kózlerine qan tolǵan. Shashları mısalı jabaǵı turǵan (Á.Shamuratov)."},
    { word: "Adasıw", meaning: "f. 1. Jańılısıw, qátelesiw, joldan shıǵıw. 2. Jol tappaw, joldan shıǵıw, bilmey qalıw.", experience: "Aqmaq gáwir adastıń. Kúnde júrer jolıńnan («Er Ziywar»). Adamzat ay bolmasa adasadı, kewildi sóylespesen kir basadı (qq.x.q.)."},
    { word: "Advokat", meaning: "at. Zań xızmetkeri, birewdiń qılmıslı isi boyınsha sud aldında qorǵawshı, aqlawshı, jaqlawshı."},
    { word: "Adres", meaning: "at. Turatuǵın jer, mákan, mánzil.", experience: "Konverttiń sırtındaǵı jiberiwshiniń adresin oqısam «Karimov Abıldan» depti (A.Bekimbetov). 2. Birewge qaratılǵan sóz, zat. Bunıń ózi de meniń adresime bolǵan kritika (T.Nájimov)."},
    { word: "Adresat", meaning: "at. 1. Xat yamasa bir zattıń tapsırılatuǵın adamı, iyesi. 2. Yubiley jasındaǵı adamǵa yamasa mekemelerge beriletuǵın qutlıqlaw xatı.", experience: "Kóp xatlardıń arasında ayırım adresat belgisiz bolıp shıqtı (A.Bekimbetov). Adresat tabılmaǵanlıqtan xat qaytarıldı (A.Bekimbetov)."},
    { word: "Adım", meaning: "at. 1. Qádem, adam júrgende alǵa qaray taslanǵan qádemindegi eki ayaqtıń arası (aralıq jer). 2. Jetiskenlik.", experience: "Dárriw alǵa qaray altı-jeti adım attı (Q.Ayımbetov). Biraq bul tek dáslepki adımlar ǵana edi (Á. Shamuratov)."},
    { word: "Adırayıw", meaning: "f. Eleriw, tańlanıw, kózin shennen tıs ózgeshe etip qaraw, úreyleniw, ashıwlanıp qaraw.", experience: "Qurban kókshi balasına adırayıp bir qaradı da, Palmannıń sózine qalay juwap qaytarıwdıń jolın izledi (M.Abdraymov)."},
    { word: "Adır", meaning: "kel.Tegis emes, jol túspegen, ısılmaǵan.", experience: "Adır-adır tawlardan, Ardaqlay berip qashadı, Gúdir-gúdir qumlardan, Gúdirleydi basadı («Máspatsha»)." },
    { word: "Adıraq", meaning: "kel. Adırıq kóz, ádettegiden úlkenirek, adırayǵan, kózi baqanshaqtay.", experience: "Kózi úrkken tananıń kózindey adıraq kóz bir qız keldi (A.Begimov). Joq, bunday emes, dep esik jaqta bir betkey otırǵan adıraq kózli, jalpaq bet, aq quba jigit juwap berdi (K.Sultanov)."},
    { word: "Adır-budır", meaning: "kel. Jónli-jónsiz, qalay bolsa solay, áytewir, tegis emes.", experience: "Qızdıń jolı názik, oǵan adır-budır sóz aytıwǵa bolmaydı (M.Abdraymov)."},
    { word: "Ajar", meaning: "at. Kelbet, shıray, túr, tús, sımbat.", experience: "Betinde ótkir ajarı, beyish suwın ishkendey (Q.Maqsetov)."},
    { word: "Ajırasıw", meaning: "f. 1. Ayra túsiw, tarap ketiw, ayırılısıw, ayırılıp qalıw, bólekleniw, qol úziw. 2. Erli-zayıplılardıń nekesin buzıp, ayırılısıwı.", experience: "Balalardan ajırasqannan soń Turım iytler shabalanǵan jerge jaqınlap keldi de, suwınlap jıynalǵan pishenniń tasasınan sıǵaladı (K.Sultanov). Hásiret-qayǵı zil basıp, aqılınan ajırasıp (A.Dabılov)."},
    { word: "Ajırıq", meaning: "at. Tamırı jayılıp ósetuǵın kóp jıllıq jabayı mayda shóp.", experience: "Izimdi taǵı bilmesin dep ajırıqtıń ishi menen úyge qayttım (J. Aymurzaev).... úyine shekemgi ajırıq basıp jatatuǵın aralıq ajırıqlıqqa aylanıptı (T. Qayıpbergenov)."},
   { word: "Az", meaning: "r. 1. Jetkiliksiz, kóp emes, barlı-joqlı, az ǵana, azǵantay.", experience: "Bir qatar joldaslar menen sóylesip qarasam kúsh az deydi (K.Sultanov). Ol az ǵana tunjırap otırdı (K.Sultanov)."},
    { word: "Aza", meaning: "at. Tuwısqan, jaqın-juwıq qaytıs bolıwına baylanıslı qayǵırıw, matam tutıw.", experience: "Urıs-ólige aza, tirige-tamasha degen eken (A.Bekimbetov). Tańdı doslarım jaranı, Hesh qashırmadı arasın, Kiyinip ústine qaranı, Kóp jılasıp tuttım aza (Berdaq)."},
    { word: "Aza ton", meaning: "at. Aza ushın kiygen qara, kók kiyim.", experience: "Aza tonın jamılıp, Ata-anamnan ayırılıp (Berdaq)."},
    { word: "Azada", meaning: "kel. Tazalıqlı, taq-tuynaqtay, duwpiyaz.", experience: "Narzan bulaqları qanday azada, Seniń kewliń yanlı, tınıq hám taza (I.Yusupov). Azada qızlardıń qoynı, Jánnettiń baǵına megzer (Ájiniyaz)."},
    { word: "Azamat", meaning: "at. 1. Kámalǵa kelgen er adam. 2. Adamgershiligi bar, sana-sezimli, xúrmetli adam. 3. Adam atı, isim.", experience: "Azamat erdiń belgisi, az ǵana sóylep kóp tıńlar, arǵımaq attıń belgisi, az ǵana otlap kóp juwsar (qq.x.q.). Tuwrı tutsan niyetińdi, Xalıqqa bursań betińdi, Sıylasań ǵárip jetimdi, Shın azamat boladursań (Berdaq)."},
    { word: "Azamatlıq", meaning: "kel. Erlik, batırlıq, is meńgere alatuǵın, óz wazıypasın atqara biletuǵın.", experience: "Jas balanıń erlik, azamatlıq isine kewli tolǵan kapitan Sultannıń mańlayınan súyip aldı (A.Bekimbetov). Iske tayar turıw-azamatlıq is, Márt bolsań el ushın jumsań jiger-kúsh (X.Seytov)."},
    { word: "Azan", meaning: "at. 1. Tań atar mezgil, erte waqıt. 2. din. Elattı namazǵa shaqırǵanda yamasa tuwılǵan nárestege at qoyǵanda aytılatuǵın namazdıń kirispe bólimi.", experience: "Allambergen aǵa azanǵı chaydı iship otırǵanda men de kirip barǵan edim (J.Aymurzaev). Azanǵı shıq penen aq pishendi sáskege shekem orıp qaytadı (K.Sultanov). Azan aytıp Alla dep, Erteli kesh baqırar («Er Ziywar»). Mázin namazsham namazınıń azanın jańa ǵana ayttı (L.N.Tolstoy)."},
    { word: "Azan-ǵazan", meaning: "r. Uw-shuw, baqırıs, ala topalań, tártipsiz, qalay bolsa solay, biytártip.", experience: "Mallar da... mónirep awıldıń arasın azan-ǵazan qıldı (M.Abdraymov). Muz ıqqannan beri awıl arası azan-ǵazan boldı (M.Abdraymov). Mónirep kiyatırǵan árwana sıyırlardıń dawısı biydiń basın azan-ǵazan etti... (K.Sultanov)."},
    { word: "Azanlı-keshli", meaning: "r. Mezgili menen, azanda da, keshte de, bárhama.", experience: "Qas qaǵıp, sharap ishpege, Taraqlap belden qıspaǵa, Azanlı-keshli túspege, Sárhawızıń tur Qulen bolıs (Berdaq)."},
    { word: "Azap-aqıret", meaning: "at. Qıyınshılıq, jamanlıq, zulımlıq, qayǵı-hásiret, ıza, qorlıq, zorlıq-zombılıq.", experience: "Húrlimannıń baqsı bolǵanın Qaraqumnıń iyshanı esitip, shaqırtıp alıp Berdaqqa kóp azap-aqıretler beredi (Q.Ayımbetov)."},
    { word: "Azaplaw", meaning: "f. Qıynaw, zorlıq kórsetiw, jábirlew, azap beriw, qorlaw, zorlıq etiw.", experience: "Joq... gúmansız, haq qızdı sawal-juwapqa tutıp azaplawıńızǵa jol qoymayman (R.Tagor). Biraq, batırdı azaplaw da, zindan da, dar da qorqıta almadı (Q.Maqsetov)."},
    { word: "Azar", meaning: "at. Azap-aqıret, qıyınshılıq. Azar shegiw-qıynalıw. azaplanıw, aqıretleniw. Azar beriw-qıynaw, azap beriw, aqıretlew.", experience: "Bunday azarǵa kóniwge bolmaydı (M.Gorkiy). Men bunnan azar shegip, zordan júrmen (Q.Jumaniyazov). Azar bermey oyatıp, Kelgendegi jumısın, Aydosqa bular aytadı (Berdaq). Kelgen razvedchiklerden eki adam jeńil jaralanǵan, biraq júriwge jaraları azar bererlik emes (Q.Dosanov)."},
    { word: "Azat", meaning: "at. Erkin, ǵárezsiz, bostan, óz erki ózinde, qolı bos.", experience: "Jaqsılıq xabar alıp kelgen Ótemurat edi, Ernazardıń azat bolǵanına ayaǵı sayǵa tiymeydi (K.Sultanov)....úyge ákelip baspaǵıma, az ǵanasın saldım, endi men úy jumısınan da azatpan (Á.Shamuratov)."},
    { word: "Azat etiw", meaning: "f. Erkin etiw, bostanlıqqa shıǵarıw, erkti ózine beriw, basın bosatıw.", experience: "Olardıń tiykarǵı wazıypası adamlardı baylardıń ómiri menen onıń ámeldarlarınıń zulımınan azat etiw (S.Ayniy)."},
    { word: "Azat etiwshi", meaning: "at. Óz erkine jiberiwshi, bostanlıqqa shıǵarıwshı, erk beriwshi, huqıqın alıp beriwshi.", experience: "Koreya menen Qıtaydıń azat etiwshi armiyası basqınshılardı Koreyadan quwa baslaǵan (J.Aymurzaev)."},
    { word: "Azatlıq", meaning: "at. Bostanlıq, darqanlıq, erkinlik.", experience: "Aqtı gúwlep azatlıqtıń dáryası, Háddiń joq baylawǵa shalqar saǵası (K.Sultanov)."},
    { word: "Azbaw", meaning: "f. Adaspaw, jańılıspaw, degbirden saspaw, ózgermew, albıraqlamaw, aynımaw.", experience: "Men oǵan joldan azba dep urısaman (Q.Sultanov). Adamnan azǵan jabayı jırtqısh, qanǵa qumar zalım (Q.Dosanov)."},
    { word: "Azǵan", meaning: "f. Aynıǵan, awǵan, ózgergen, buzılǵan.", experience: "Fashist adamnan azǵan jabayı jırtqısh, qanǵa qumar zalım (Q.Dosanov)."},
    { word: "Azǵırıw", meaning: "f. Aynıtıw, úgitlew, buzıw, sóz beriw.", experience: "Aldanıp turıpsań shınnan berilip, Azǵırıp sózine babanın erip («Máspatsha»). Kópshilik aǵayin azǵırıp, aqırı Sarıgúldiń de wádesin aldı (K.Sultanov)."},
    { word: "Azday", meaning: "r. Azıraq qusaǵan, jetkilikli emestey, jetpegendey.", experience: "Kósew qılıp qoyǵanı azday, xan elimizdi talatadı (T. Qayıpbergenov). Meniń burınǵı dártim azday, ákemniń egil-tegil bolıp jılawı dárt ústine dárt jamap júregimdi parra-parra etip jaraladı (Ó.Xojaniyazov)."},
    { word: "Azdan", meaning: "r. Az-azdan, kem-kemnen, birden emes, keyinirek, sońınan, birimlep.", experience: "Azdan soń umıtıp qalǵan qarmaqlarımdı alıwǵa kelsem, ákem úyde joq eken (K.Smamutov). Azdan soń Mısqal peri oyanıp qarasa, qasında bir jigit sulap jatır (Q.Ayımbetov)."},
    { word: "Azlap", meaning: "r. Azıraq, azı-kem, ebindey, kóp bolmasa da.", experience: "Ishimizde Samender degen bir jigit bar, ol sol waqıtta azdan qosıq shıǵaratuǵın hám qaraqalpaq namaların da jaqsı biletuǵın edi. Seni azlap tanıyman, azı-kem bilemen... (Ó.Xojaniyazov)."},
    { word: "Azlaw", meaning: "r. Azıraq, kemirek, shamalı, azı-kem, sál, bolar bolmas.", experience: "Bul maǵan azlaw balam, - dedi ǵarrı (gazetadan)."},
    { word: "Az-maz", meaning: "r. Qurttay, shamalı, azıraq.", experience: "Az-maz jılınıp alsaq qalay bolar eken, - dedi ol (A.Áliev). Qız maǵan az-maz qarap turǵansha jańaǵı kelinshek penen shıǵıp ketti (G.Izimbetov)."},
    { word: "Azna", meaning: "at. Adamlar otırıw ushın qayıqtıń ústindegi kese tartılǵan aǵashı.", experience: "Bir kisi, Egor ma deymen, ayaǵın aznaǵa tiredi («Sálem Oktyabr» T.). Otız kemeniń aznası Sóz xalıqtıń ǵaznası (qq.x.n.)."},
    { word: "Aznaw", meaning: "f. Kisnew, maldıń shuwlawı, qayǵılı dawıs shıǵarıw.", experience: "At qalǵanın ańlap, Nala tartıp aznadı («Alpamıs»)."},
    { word: "Azshılıq", meaning: "at. Az sanlı, az muǵdar.", experience: "El qurıldı shaqaplandı jurtshılıq, Xızmetkerler ádep qıldı azshılıq (Q.Irmanov)."},
    { word: "Azıq-túlik", meaning: "at. Azıq-awqat, kerek-jaraq.", experience: "Beldarshılar hám onıń bala-shaǵaları izli-izinen kelip, azıq-túliklerin arbaǵa salıp atır (K.Sultanov). Ekewiniń de ústinde ele tozıwı jete qoymaǵan áskeriy kiyimler, qollarında azıq-túligi (Q.Dosanov)."},
    { word: "Azıqshı", meaning: "at. Azıq beriwshi, azıq tarqatıwshı, azıqtı jetkeriwshi, azıq tasıwshı.", experience: "Azıqshını ishke kirgizbey, bendelerge qarawıllar úlestiretuǵın edi (T.Qayıpbergenov)."},
    { word: "Azımshıq", meaning: "kel. Ádewir, bir talay, oǵada, keskinsiz, az emes, biraz, táwir-aq, bir qıylı.", experience: "Biz bul jerge azımshıq miynet etkenimiz joq (Ó.Xojaniyazov). Bılshıyǵan dep betindi, Azımshıq emes sın taqtı («Qırq qız»)."},
    { word: "Azınawlaq", meaning: "r. Azǵana, kóp emes, jarım-jartı, shamalı, bolar-bolmas, kemirek.", experience: "...azınawlaq kún generaldıń jerinde erksiz jumıs isleydi (Q.Dosanov)."},
    { word: "Azıp-tozıw", meaning: "f. Boldırıw, júdep qalıw, moy beriw, albıraw.", experience: "Kúni-túni tınım tappay zır juwırıp júrgen záberdes kelinshek tórt-bes aydın ishinde-aq azıp-tozıp qaldı (A. Bekimbetov)."},
    { word: "Azıw.I", meaning: "at. Tańlay tis, úlken tis, ótkir, mıqlı, awızdıń eki qaptalında awqat jew ushın eń kereklisi.", experience: "Azıw tislerinen álle qashan ayırılıp qalǵan (J.Aymurzaev)."},
    { word: "Azıw.II", meaning: "f. Boldırıw, júdew, arıqlaw, buzılıw.", experience: "Zaman qısletinen sarǵaydım azdım. Bolar ma dep jaqtı kúnler xalıq ushın (Berdaq). Aq kewilliniń atı azbaydı, tonı tozbaydı (qq.x.n.)."},
    { word: "Azıwday", meaning: "kel. Azıwǵa usaǵan, azıw sıyaqlı mıqlı.", experience: "Jetimlerden hám biy, bay balalarınan qay-naqay azıwday eliw atlı (T.Qayıpbergenov)."},
    { word: "Azıwlasıw", meaning: "f. Ayqasıw, urısıw, qarsılasıw, ashshılasıw, dushpan menen sınasıw, tislesiw, shayqasıw.", experience: "Hesh waqta shoshqa shoshqanı, Azıwlasıp jarǵan emes (Berdaq)."},
    { word: "Azot", meaning: "Tógin, dáris ushın paydalanılatuǵın ximiyalıq element.", experience: "Azottıń, fosfordıń hár gektarǵa qansha ekenin aytıp otırmayman (Q. Dosanov)."},
    { word: "Azsınıw", meaning: "Kemissiniw, kewli pitpew.", experience: "Azsınıp tursız ba aǵa, jigitlerdiń de tabısın kóremiz (K. Sultanov)."},
    { word: "Azbıray", meaning: "Qural-ásbap, qural-sayman, kerek-jaraq."},
    { word: "Azıq", meaning: "Awqat bolatuǵın nárseler.", experience: "Altı qız minip arbaǵa, azıǵın salıp dorbaǵa, aytıw-mereke barmaǵa, qızlar talap etken eken (Berdaq)."},
    { word: "Azıraq", meaning: "Azǵana, shamalı, kishkene, kóp emes.", experience: "Tamaqtan awıstırıp tuqımǵa saqlaǵan azıraq arpa-jazlıq bar edi, - dedi Turımbet (N.Dákaraev)."},
    { word: "Azıw", meaning: "Tanlay tis, úlken tis, ótkir, mıqlı.", experience: "Azıw tislerinen álle qashan ayırılıp qalǵan (J.Aymurzaev)."},
    { word: "Azǵın", meaning: "Júdew, arıq, eti ketip súyegine taqalǵan, boldırǵan.", experience: "Betinde qan joq, azǵın (T. Qayıpbergenov)."},
    { word: "Aybana", meaning: "at. Qáwender, arqa súyer, tirenish, qorǵanısh, abay, súyenish, tirek."},
    { word: "Ayǵır", meaning: "at. Úyirde pishilmegen erkek jılqı.", experience: "Atıń ayǵır bolsa, jat ta qayǵır (kk.x.n.)."},
    { word: "Ayda", meaning: "f. Júrgiz, aldına sal, jolǵa sal, jolǵa túsir, tart jónine ket.", experience: "Ne de bolsa baxtıńnan kórerseń, ayda awılıńa (Ó.Xojaniyazov)."},
    { word: "Ayda-jılda", meaning: "r. Anda-sanda, ara-tura, hár waqta.", experience: "Awıl úydiń qonaǵı ayda-jılda bir keledi (kk. x.n.). Ayda-jılda bir kelippen, Aq júzińdi kórmege (Q.Ayımbetov)."},
    { word: "Ayday", meaning: "kel. Ay sıyaqlı, ay taqıletli, jaqsı, sulıw, júdá jaqsı, aytıwlı.", experience: "Jarqıraydı betiń ayday, Tuwǵan anań seniń qanday, Sóziń shiyrin, tiliń palday, Periyzattan artıq kelin (Berdaq)."},
    { word: "Ay júzli", meaning: "kel. Ayrıqsha sulıw, ay menen kúndey.", experience: "Ay júzli, pal sózli, dilbarım nege kelmedi (Ájiniyaz). Ay júzi kúndey nurlanıp, Júregi hallas urǵan qız (B.Qayıpnazarov)."},
    { word: "Ayqay", meaning: "at. Baqırıs, badabad, shawqım, kózaba.", experience: "Shıday almay jigitler qurı ayqay saladı («Qırk qız»)."},
    { word: "Ayqulaq", meaning: "at. astr. 1. Nur hám suw tamshılarınan payda bolatuǵın forması reńli yarım ay taqılettegi atmosferalıq qubılıs. 2. Adamlardıń, janlı-janıwarlardıń qulaǵınıń artqı súyek forması.", experience: "Tekeniń saqalınıń astında uyqılap jatqan bir ǵarrınıń kózine bir ayqulaq túsedi (qq.x.e.)."},
    { word: "Ayqulash", meaning: "at. Oyınnıń atı, eski oyınlardıń bir túri.", experience: "Ayqulash, ayqulash, Ayǵa qarap qulash ash, Aydan basqa kim kerek, Aydan artıq qız kerek (qq.x.e.)."},
    { word: "Ayqın", meaning: "kel. Ashıq, anıq, belgili, naqma-naq.", experience: "Máspatsha dástanında xalıqtıń ótkendegi Turmısınıń ayqın kartinaları súwretlengen (kiris sóz). Buǵan onıń mınaday shın danalıq sózleri ayqın dálil (I.Saǵitov)."},
    { word: "Ayqırıw", meaning: "f. Baqırıw, qıshqırıw.", experience: "Mine zavod birese berdi ayqırıp, Bir baqırdı poezd oǵan tay turıp (T.Seytjanov)."},
    { word: "Aylana", meaning: "at. Qır dógerek, átirap, ján-jaq, tórt tárep.", experience: "Biziń komandir bizdi kózi menen bir sholıp aylanaǵa qaradı (ád. jıyn.). Aylanasına úlken mazmun toplawı menen ulıwma ádebiyatımızdıń jolın baslap júrdi (G.Esemuratov). Aylana jiyek qaraydı (qq.x.q.)."},
    { word: "Aylanba", meaning: "at. Burılıs, joldıń aylanıp ótetuǵın jeri.", experience: "Tank joldıń aylanbasına kelgende, onıń shep búyiri Quwanıshtıń nıshanasına dál keldi (Q.Dosanov)."},
    { word: "Aylap", meaning: "r. Aylar boyı, kóp waqıtlar.", experience: "Sonlıqtan suw tasıw máwsiminde qayıqqa mútáj awıl bir-birine eki-úsh aylap qatnasa almadı (K.Sultanov)."},
    { word: "Aylı", meaning: "kel. Ayı bar, ay jarıǵı túsken tún, aylı tún.", experience: "Tumlı-tusın túrli gúl basqan, Sup-sulıw, aylı kóshede (B. Qayıpnazarov)."},
    { word: "Aylıq", meaning: "at. 1. Aqsha, pul, is haqı. 2. Waqıt, mezgil, muǵdar.", experience: "Vedomost boyınsha aylıq alıw. Jamanǵa tún de qaranǵı, kún de qarańǵı, oshaqtıń ush-pushı úsh aylıq jol (qq.x.e.)."},
    { word: "Ayma-ay", meaning: "r. Ay sayın, hár ayda.", experience: "Kún sayın kórkeyip, ósip ayma-ay, Óshpes baxıt nurın shasha basladı (S.Nurımbetov)."},
    { word: "Aymaq", meaning: "at. Bir betkey jer, átirap, dógerek, óz aldına bir bóleklengen kólemli jer, bir topar qonıslasqan xalıq.", experience: "Aynalayın, aymaǵım, shóllegende suwsınım (qq.x.q.). Qızdı oradı mamıqqa, Baǵıw ushın may, qaymaqqa, Bildirmey awıl-aymaqqa, Óz islerin etken eken (Berdaq)."},
    { word: "Aymalaw", meaning: "f. Álpeshlew, erkeletiw, jubatıw, aldastırıw, sıypalaw, qádirlew.", experience: "Sol uyadan túlegenmen, ushqanman, Talay dawıl aymalaǵan tósimdi (I. Yusupov)."},
    { word: "Aymanday", meaning: "kel. Tap-taza, pákize, kewildegidey, tep-tegis, bir tegis, tap-taqır, mıstay.", experience: "Úydiń dógeregi aymanday, tap-taza etip qoyıldı, ... (gazetadan)."},
    { word: "Ayna", meaning: "at. 1. Bir nárseniń kórinisin qayta sáwlelendiretuǵın zat, buyım. 2. Jayǵa jaqtılandırıw hám hawasın tazalaw ushın qollanılatuǵın qurılıs buyımı.", experience: "Ayna kerek bolsa júzin kóriwge, Suw da kerek jasap ómir súriwge (Ád. al.). Ayna aldında qońır tartsa da, xalıq aldında júzlerin jarqın (G.Esemuratov)."},
    { word: "Aynaday", meaning: "kel. 1. Taza, tap-taza, girbińsiz, gúmansız, 2. Aynaǵa usaǵan, ayna yańlı.", experience: "Uyalǵan tek turmas degendey etiginiń tumsıǵı menen sırlı edenniń aynaday júzin qırshıdı (A. Bekimbetov). Injenerdiń aynasınan, Túnlerde sónbes jaqtı (I.Yusupov)."},
    { word: "Aynalıp-úyiriliw", meaning: "f. Qayırqomlıq kórsetiw, ǵamxorlıq etiw, kútimin beriw.", experience: "Qaptalına kelgen aq tazını aynalıp-úyirilip, eki kózin sıypap tur (K.Sultanov)."},
    { word: "Aynanayın", meaning: "T.s. Adamnıń birewdi jaqsı kórip ózine tartıw sezimi.", experience: "Aynanayın, appaǵım, Qozı júnli qalpaǵım (Q.Ayımbetov). Perzentindey kúlip oǵan der eljirep: aynanayın (I.Yusupov)."},
    { word: "Ayna-taraq", meaning: "at. Hayal-qızlardıń kerek jaraǵı, aynası, taraǵı t. b. zatları.", experience: "Ayna menen taraq bar, Almasań da qarap qal (qq.x.n.)."},
    { word: "Ay nurı", meaning: "at. Ay sáwlesi, ay jarıǵı.", experience: "Ekewi de qumar eter tún gezip, Ay nurına júzi gúl-gúl janıptı (T.Seytjanov)."},
    { word: "Aynımaǵan", meaning: "kel. Dál ózi, usaǵan, tap ózindey, ózgermegen."},
    { word: "Aynıtıw", meaning: "f. Ózgertiw, buzıw, sóz beriw, basqa jaqqa dóndiriw.", experience: "Hayalın aynıtıp júrgeni de ıras, otinishimizdi pitirmeseń kórermizdaǵı, dep ketkeni de ıras (Q. Irmanov)."},
    { word: "Ay-pay: ay-payına qaramaw", meaning: "r. Áyle-páylesine qaramaw, olay-bulayına qaramaw, tezletiw.", experience: "Aytbaydıń ay-payına qaratpay: Aq patshanıń hámirine muwapıq márdikarǵa alındıń, jaqında keteseń, dedi (M.Dáribaev)."},
    { word: "Aypap-jaypaw", meaning: "r. Basqılaw, jaypap taslaw, búldiriw."},
    { word: "Ayraq-tayraq", meaning: "kel. Qalay bolsa solay, áytewir, parıqsız, retsiz, tártipsiz, jónli-jónsiz.", experience: "Sonlıqtan onı ayraq-tayraq etip jazılǵan qoljazbalar qorqıttı (Yu. Leontichev)."},
    { word: "Ayralıq", meaning: "at. Judalıq, intizarlıq.", experience: "Kútilmegen ayralıqtıń azabı, Qayıspastay jas kewilge dárt saldı (I. Yusupov). Eki ashıq bir qosılıp júre almay, Ayralıqtan biri-birin kóre almay (A.Dabılov)."},
    { word: "Ayran", meaning: "at. Aǵarǵannıń bir túri, qatıqtı pisip mayın alǵannan keyingisi.", experience: "Ayran tilep kelipseń, shelegińdi jasırma (qq.x.n.)."},
    { word: "Ayran-shalap", meaning: "at. Aǵarǵannıń túri, qatıq, sút, suw qosılǵan aǵarǵan.", experience: "Kúni menen jol qaqqan jolawshılar ayran-shalapqa qayıl (X.Seytov). Buyaqtaǵı kórgen qorlıq-azap shay ornına ishken ayran-shalaptı. Qushaqlasıp aytatuǵın kún qayda? (Kúnxoja)."},
    { word: "Ayrı", meaning: "at. Temir jaba, eki yamasa úsh-tórt tisli, ayrı tis, ushı eki ayrı.", experience: "Chaydı qoy, pátirdi qoy, qolıńa ayrı, arqan al (Ájiniyaz)."},
    { word: "Ayrıqsha", meaning: "r. Óz aldına, erekshe, bir bólek, ózgeshe, kewil awdararlıq, bólekshe.", experience: "Batır tuwǵan atadan, Ayrıqsha tuwǵan anadan, Aydos degen babamız, Xandı kózge ilmedi (Berdaq). Kópshiliktiń arasınan álle birewdiń dawısı ayrıqsha shıqtı (Ó.Ayjanov)."},
    { word: "Ayırılmas", meaning: "kel. Ayırılmaytuǵın, bekkem, ózgermeytuǵın, ajıralmas, bóleklenbeytuǵın, tıǵız.", experience: "Shamurat penen Grisha ayırılmas dos edi (Q.Dosanov), Surtayshadan bul qayǵımdı alıńlar, Ayırılmas basına qayǵı salıńlar («Qırq qız)."},
    { word: "Aysız", meaning: "kel. Ay batqanda, ay tuwmay turǵanda, qaranǵıda.", experience: "Aysız túnde jol júriw qanday qıyın (Ó.Ayjanov). Aysız qarańǵı túnlerdiń biri edi (ád. xrest.)."},
    { word: "Ayt I", meaning: "f. Sóyle.", experience: "Meyli, biraq tez ayt. (A.Áliev.)."},
    { word: "Ayt II", meaning: "at. Bayram, mereke, toy-tamasha.", experience: "Aytlar aytlap, toylar toylap júrgende, Biziń eldiń keliniseń degen sóz. Ata-anam qulaǵımnan ketpeydi («Alpamıs»)."},
    { word: "Ayta-ayta", meaning: "f. Qayta-Qayta ayta beriw, tákirarlap aytıw.", experience: "Basıńda bolmasa taǵıń, Ayta-ayta talar jaǵıń (Berdaq). Oqıp shıqtım qayta-qayta, Júrdim onı ayta-ayta, Kóp oyladım dep pe qáte. Tariyxın bilmegen edim (Berdaq)."},
    { word: "Ay", meaning: "Aspan denesi, jerdiń joldası, belgili bir muǵdar ishinde túnge jarıq berip turatuǵın aspan keńisligindegi dene.", experience: "«Esime túser meniń, Suw boyına kelgeniń, «Ay ne ushın jalǵız» dep, sırlı sawal bergeniń... (I.Yusupov)."},
    { word: "Aybalta", meaning: "Baltanıń qural ornına qollanılatuǵın ádette, patshalar qolına alıp otıratuǵın quralı, jaraq.", experience: "Sol waqıtları Surtaysha, Aybaltası qolında, Alarıp turdı ornınan («Qırq qız»)."},
    { word: "Aybaraq", meaning: "Bada-bad, aybat, abay-siyasat.", experience: "Qolǵa uslap jaw-jaraǵın, Salıp bular aybaraǵın, Siltedi barlıq jaraǵın, Qızdı baylap almaqshı eken (Berdaq)."},
    { word: "Aybat", meaning: "Túr-tús, qáhár, saltanat.", experience: "Buzaw iytlerge aybat etti, Perigúl jibermey, moynınan qatıp uslap tur (Ó.Ayjanov)."},
    { word: "Aybatlı", meaning: "Ǵayratlı, qáhárli.", experience: "Atam aybatlı kisi edi (S.Saliev)."},
    { word: "Aybınıw", meaning: "Tartınıw, batına almaw, qorqıw.", experience: "Gá bir qaytpalardan aydarlı ushan keme aydaǵan darǵashılar da aybınıp ótedi (K.Sultanov)."},
    { word: "Ayǵaq", meaning: "Belgi, gúwa, dálil, kórinis.", experience: "Asfalt jolın ıǵbalınıń ayǵaǵı... (I.Yusupov)."},
    { word: "Aydala", meaning: "Alanlıq, ashıqlıq, maydan, elsizlik, adamsız, elsiz, qula dúz.", experience: "Kewli tolıp óz isine Jumannıń, Aydalada kókti gezdi qıyalı (T.Seytjanov)."},
    { word: "Aydar", meaning: "Belgi, jas balalardıń tóbesine qoyılatuǵın bir tal shash, tulım.", experience: "Mamannıń qalpaǵın alıp aydarınan bir súydi (T.Qayıpbergenov)."},
    { word: "Aydın", meaning: "Ashıqlıq, kólat, jazıqlıq, tegislik, tuwra jol, ashıq, taza, keńislik.", experience: "Aydın kólden payda joq, Razı bolmasa kelinde («Er Ziy war»)."},
    { word: "Ayqas", meaning: "Urıs, jekpe-jek, jánjel, gúres.", experience: "Jańa turmıs ushın ayqas jolında, júr edim, ol maǵan jolıqtı sonda (I.Yusupov)."},
    { word: "Aylaw", meaning: "At jarısınıń belgili bir muǵdardaǵı shawıp keletuǵın yamasa shawıp ótetuǵın jer ólshemi."},
    { word: "Aytıs", meaning: "Folklorlıq keyingi janr.", experience: "Usınday házil aytıstan keyin Berdaq penen Ótesh shayır ekewi qattı dos boladı (I.Saǵitov)."},
    { word: "Ayıpker", meaning: "Gúnalı, ayıplı, qılmıslı, ayıpdar.", experience: "Joq men ayıpsız ayıpkermen (A.Bekimbetov)."},
    { word: "Aytaqır", meaning: "at. 1. Alańlıq, dalalıq, maydanlıq, keń jazıqlıq. 2. Joqshılıq, kemtarlıq.", experience: "Ushı aytaqır ushı qıyrı menen shet-shebirine kóz jetkisiz, Shelpekliniń dalası (Ó.Xojaniyazov.)"},
    { word: "Aytar", meaning: "f. Aytatuǵın, aytajaq.", experience: "Ǵarrı Sheripke aytar sózin aytıp boldı (K.Irmanov). Aytarımdı ayttım da, ózimdi áwelgiden bir qansha jeńil sezdim (Ó.Xojaniyazov)."},
    { word: "Aytsa", meaning: "f. Ayt feyiliniń shárt forması."},
    { word: "Aytım", meaning: "at. Toylarda, betasharlarda, qız-jigit otırıspalarında aytıstıń túrleri, óli ólgen jerde joqlaw (aytım) aytıp jılaw t.b. jaǵdaylarda qollanılatuǵın sóz.", experience: "Aytım aytqan qáynińdi, sıyla, sıylama ózin bil (kk.x.s.j.). Qáne, aytım aytatuǵınlarıńız bar ma? («Ámiwdárya» j.)."},
    { word: "Ayshıq", meaning: "at. Burınǵı waqlarda, hayal-qızlardıń bezeniw ushın ónirine taǵatuǵın zatlarınıń bir túri.", experience: "Qubıljıtıp naǵıs oyǵan alqımdaǵı ayshıq súyek, Súynementtey sawrı betke omırawdan tústi qulap (I. Yusupov)."},
    { word: "Ayı", meaning: "at. 1. Kúni, waqtı, mezgili.", experience: "Salqın tartqan gúz ayınıń tańı onıń sharshaǵan ıssı denesine jaǵımlı tiydi(A.Bekimbetov)."},
    { word: "Ayıǵıw", meaning: "f. Dúzeliw, táwir bolıw, jazılıw, kelege keliw, jaqsarıw, qáddine keliw.", experience: "Kóp keshikpey ol usı awırıwınan ayıqtı (Ó.Ayjanov)."},
    { word: "Ayı-kúni", meaning: "at. Waqtı, mezgili.", experience: "Kórinler bul hasıl zattı, Esitińler iltifattı, Qádir aqsham tolǵattı, Ayı-kúni tolǵan eken (Berdaq)."},
    { word: "Ayıl", meaning: "at. Teletińnen islengen, minis kóligin ertlegende onıń belinen shalatuǵın (oraytuǵın yamasa belinen baylaytuǵın), erdiń awmawı ushın onı bekkemlep kóliktiń arqasına tańıp qoyıw ushın arnalǵan qural-saymanlardıń biri.", experience: "Atlarǵa erdi salayıq, Ayıldı bekkem shalayıq («Qırq qız»)"},
    { word: "Ayıp", meaning: "at. Ersilik, gúnakarlıq, hádden tıs háreket, qátesi, gúnası, jaman  is.", experience: "Haw gúbelek, maqtanasań shalqayıp,  Bilmey turıp kemis  tapsań bul - ayıp (I.Yusupov)."},
    { word: "Ayırma", meaning: "at. Parıq, ózgeshelik, basqalıq, belgi."},
    { word: "Ayırım", meaning: "r. Bólek, óz aldına, bazıbir, geybir.", experience: "Qaraqalpaq jerine xızmetke kelgen, kelip islegen ayırım rus adamları da úlkeni úyreniw menen shuǵıllana basladı (B.Ismaylov). Hár kimniń xojalıǵı ayırım, ózlerine dárek bólmesi boladı (T. Qayıpbergenov)."},
    { word: "Ayıw", meaning: "at.  Jabayı haywan.", experience: "Jalǵızlıq penen azlıqtıń, dáwiri ketti kelmeske, Bólinseń bóri ayırılǵan, Adamdı ayıw jemes pe?! (I. Yusupov)."},
    { word: "Akademik", meaning: "at. Ilimiy ataq, eń joqarı ilimiy dáreje, Ilimler akademiyasınıń haqıyqıy aǵzası.", experience: "Akademik Aybek shayır, Ǵafurday, Hár bir sózi tobılǵınıń torınday (K.Sultanov)."},
    { word: "Akademiya", meaning: "at. Eń joqarǵı ilimiy mákeme. Ilimler akademiyasınıń sessiyası."},
    { word: "Akaciya", meaning: "at. Terektiń bir túri, gúlleydi, aq gúlli hám jaqsı iyis beredi.", experience: "Muhabbattıń urıǵınday, ósti bir túp akaciya (I. Yusupov)."},
    { word: "Akkordeon", meaning: "at. Muzıqalıq saz ásbabı. Akkordeon shertiw."},
    { word: "Akrobat", meaning: "at. Cirkte gimnastika kórsetiwshi sportshı, jeke adamnıń óz kúshi arqalı orınlaytuǵın usılı."},
    { word: "Aksioma", meaning: "at. Hesh bir dálillewdi talap etpeytuǵın ilimiy shınlıq."},
    { word: "Akt", meaning: "at. Hújjettiń bir túri. Gúwalıq ushın dúzilgen akt, ayıplaw yamasa qabıllaw ushın dúzilgen akt."},
    { word: "Aktyor", meaning: "at. Sahnada túrli sheberlik penen unamlı yamasa unamsız obrazlardı beriwshi adam, artist.", experience: "Á.Ótepov talantlı dramaturg, rejissyor hám aktyor (Á.Nasrullaev)."},
    { word: "Aktiv", meaning: "at. 1. Issheń, talapshań, shaqqan, qızǵın pát penen is júrgiziwshi kisi, belsendi.", experience: "Wazıypalı isti qarawǵa, keshte jıynalıstı qolxoz aktivi (T.Seytjanov). Kolxozlasıw dáwirinde Reypnazar júdá aktiv jumıs islegen jigit, ózi muǵallim (S.Xojaniyazov)."},
    { word: "Aktovıy", meaning: "at. Úlken, arnawlı, jıynalıslar, koncertler ótkeriwge qolaylastırıp salınǵan bólme, ójire.", experience: "Qız benen ekewimiz aktovıy zaldan shıqtıq ta, bos bir auditoriyaǵa bardıq (G.Izimbetov)."},
    { word: "Aktrisa", meaning: "at. Teatr sahnasında hár túrli pesalarda oynawshı, qosıq aytıwshı, túrli róllerdi atqarıwshı hayal.", experience: "«Aktrisanıń ıǵbalı» (I. Yusupov)."},
    { word: "Aktual", meaning: "kel. Áhmiyetli, qájetli, kerekli.", experience: "...házirgi waqıtta da aktuallıǵın joyıtpaǵan (K.Maksetov)."},
    { word: "Akusher/akusherka", meaning: "at. Náresteniń dúnyaǵa keliw procesinde medicinalıq járdem kórsetiwshi shıpaker."},
    { word: "Akcent", meaning: "at. Óz ana tiliniń seslik ózgesheliklerin basqa tilde sóylew waqtında da saqlap sóylew.", experience: "Jaqsı bolıp ketedi, qısınbań, dedi vrach qız jergilikli tilde akcent penen sóylep (A.Bekimbetov)."},
    { word: "Aq", meaning: "kel. Appaq, jaqsı, taza.", experience: "Yoshıp kewlin shadlıq artıp, Aq qaǵazǵa qálem tartıp (Á.Shamuratov)."},
    { word: "Aqaba", meaning: "at. Sırqındı, qaldıq, qalǵındı suw."},
    { word: "Aq biyday", meaning: "at. Biydaydıń sortı.", experience: "Aq biydayı turıp sulı sepkennen, Taza salı turıp shigin ekkennen. Jónsiz qırk kún qayǵı-uwayım shekkennen, Densawlıqta bir kún shadlıq jaqsıraq (Berdaq)."},
    { word: "Aqbaslıq", meaning: "kel. Aqbas shóplerdiń kóp ósken jeri.", experience: "Adam bilmes aqbaslıqta jatırman, Kerek bolsam óziń izlep tawıp al (qq.x.q.)."},
    { word: "Aq basqur", meaning: "at. Qara úydiń ózine tiyisli tiykarǵı baw-shuwlarınıń biri.", experience: "Al, endi bunıń baw-shuwı, sırtqı janbaw, ishki janbaw, aq basqur, qızıl baskur, bel jip, onı aqtan tabıw, qullası, úyge kerek-jaraqtı tabıw kerek boldı (K.Ayımbetov)."},
    { word: "Aq bilek", meaning: "kel. Tolıq, jumırı, aq, sulıw formalı bilek.", experience: "Aq bilegiń bolmasa, Altı jerden qas qoyıp, Bilezik salmaq ne payda (K.Ayımbetov)."},
    { word: "Aq boz", meaning: "kel. Túri, túsi, aq sur kóbinese attıń túrine aytadı.", experience: "Aq boz attan túsip atırǵan dostın kórdi (K.Dosanov)."},
    { word: "Aqbóken", meaning: "at. Kiyiktiń bir túri.", experience: "Maral, aqbóken qusaǵan ańlardı ǵana qaldırıp, saw-salamat eline qaytadı (qq.x.e.)."},
    { word: "Aqdur", meaning: "kel. Aq, haqıyqat, hadal, taza, pák, haq, jaqsı, eń jaqsısı.", experience: "Talap islep tap dúnyanı, Sútten aqdur bilseń anı (Berdaq)."},
    { word: "Aq egin", meaning: "at. Jazlıq, tez pisetuǵın eginniń túri.", experience: "Olardıń japlarınıń saǵasın baylap taslap, aq egin, kók egin degennen bos qaldıratuǵın edi (A.Begimov)."},
    { word: "Aq qapshıq", meaning: "kel. Oktyabr revolyuciyasınıń ornaw aldında Qaraqalpaqstanda belgili dárejede hár qıylı qıyınshılıqlar, ashlıq, áptadalıq turmıstı keshirgen xalıqtıń sol jılları belgilengen ataması.", experience: "Aq qapshıq jılı ashlıqqa shıday almay Moynaq betke kóship ketken edi (N.Dáwqaraev)."},
    { word: "Aqqas", meaning: "kel. Tawardıń bir túri, arnawlı, qádirli túri, burınları qaraqalpaq hayal-qızlardıń alıp qoyıp kiyetuǵın belgili kiyimleriniń biri esabında sanalatuǵın, arnap ózgesherek etip tigilgen kóylegi bolǵan.", experience: "Aqqas kóylek degenlerim de bar,... (A.Begimov)."},
    { word: "Aqquba", meaning: "kel. Júzi, kelbeti aq, aq reń.", experience: "Sayatxan aqqubadan kelgen, ... sımbatlı hayal (A.Begimov)."},
    { word: "Aqqula", meaning: "at. Qırmandaǵı aydalıp, tazalanǵan dánniń qır dógereklep qálbir menen hár jerinen az muǵdardaǵı alınǵan bólegi.", experience: "Aqqulasın bılay shetke shıǵarıp qoydı (N.Dáwqaraev)."},
    { word: "Aqlay", meaning: "r. Belgisiz waqta, aldınan, kún burın, aldın ala, áwel bastan.", experience: "Endigi qalǵan ómirimizde ekewimiz aqlay quda bolayıq, seniń qızıń bolsa, meniń ulım bolsa, ekewimiz shınnan quda bolayıq jora, dedi («Alpamıs»)."},
    { word: "Aqlamaw", meaning: "f. Etken miynet, ziynetlerin ótemew, kórsetken jaqsılıq, húrmetlerdi bosqa jiberiw, ótemew.", experience: "Bul isenimdi ol aqlamay qalǵan emes, planın orınlap, kóp kózine ayrıqsha túsip tur (Ó.Ayjanov)."},
    { word: "Aqlawshı", meaning: "at. Sud sistemasınıń arnawlı xızmetkeri, ayıpkerdi aqlawshı, jazasın qalay bolmasın jeńilletiwshi."},
    { word: "Aqlıq", meaning: "at. Balasınıń yamasa qızınıń balası.", experience: "Berdaq  Jiyen jırawdıń aqlıǵı Ótesh shayır menen zamanlas dos bolǵan (I.Saǵitov)."},
    { word: "Aqmaq", meaning: "at. Aqılsız, aqılı joq, biydáwlet, nadan.", experience: "Ákem jalt qarap, selk ete qaldı: - Maǵan jeńil tiyip tur deyseń be, aqmaq! — dep qattı baqırıp jiberdi (K.Smamutov)."},
    { word: "Aq mańlay", meaning: "kel. Mańlayı jazıq, mańlayı appaq, minsiz, sup-sulıw, hesh jeriniń mini joq.", experience: "Torsıq sheke aq mańlay, Kútá qızıq sózleri (X.Tájimuratov)."},
    { word: "Aqmarka", meaning: "at. Balıqtıń túri.", experience: "Aqmarqa, súyenniń hár biri qoyday, Teńizde ılaqa júzedi qoyday (A.Begimov)."},
    { word: "Aq maya", meaning: "at. Urǵashı túye.", experience: "Atqa shıqqan aq mayalı Ayjamal, Ol da sendey emes Biybigúl (Ájiniyaz)."},
    { word: "Aq orda", meaning: "at. Úskenesi jaǵınan hesh qanday kemshiligi joq, kisi tań qalarlıq etip úskenelengen, aq kiyiz benen jabılǵan 6-8 qanatlı qara úy, burınları biyler el basqarıp otıratuǵın arnawlı úy.", experience: "Jılama úkem jılama, Toy seniki yar-yar, Toqsan baslı aq orda, Úy seniki yar-yar (qq.x.s.j.)."},
    { word: "Aq otaw", meaning: "at. Aq ordaǵa qaraǵanda kishilew, aq kiyiz benen jabılǵan 4-6 qanatlı qara úy.", experience: "Patsha qaldı maqul kórip, Aq otawdıń artın túrip, Qırq qız benen dáwran súrip, Retme-ret qushqan eken (Berdaq)."},
    { word: "Aq paxta", meaning: "at. Paxta, ǵawashadan shıqqan aq paxta. ", experience: "Kóz aldında elesleydi aq paxta, Bir qanasın qoyıptı ol saqlap ta (G.Esemuratov)."},
    { word: "Aq pátiya", meaning: "at. Alǵıs, tilek, shın júrekten pátiya, raxmet.", experience: "Aq pátiya beriń dep, Biz turıppız intizar («Er Ziywar»)."},
    { word: "Aq peyil", meaning: "kel. Ak kókirek, kewli ashıq, jaman pikirsiz.", experience: "Ol sawdıraǵan aq kókirek, aq peyil hayal (Ó.Xojaniyazov)."},
    { word: "Aq porıq", meaning: "at. Kólde ósetuǵın aq tamır, qamıstıń, terektiń tamırı sıyaqlı.", experience: "Altın kún aydalanı ańlıǵanday, Aq porıq ayaq sozıp keń kólinen (G.Esemuratov)."},
    { word: "Aqpıshaq", meaning: "at. Urıwdıń atı.", experience: "Múyten, qońırat, qıtay, qıpshaq, keneges mańǵıt, aqpıshaq, Bári altı urıw qaraqalpaq sol jerden kóshkende ayırılǵan eken (Berdaq)."},
    { word: "Aqsazan", meaning: "at. Balıqtıń atı, túri.", experience: "Barıp kórsek qazaǵa, Aqshabaq penen aqsazan, Sıyǵanınsha tolıptı."},
    { word: "Aqsaq", meaning: "at. Ayaǵınıń kemisi bar, júrgende aqsańlap basatuǵın adam.", experience: "Aqsaqtıń aqırına baq. Soqırdıń sońına baq (qq.x.n.)."},
    { word: "Aqsaqal", meaning: "at. 1. Jası úlken, kópti kórgen, kóp jasaǵan, kátquda, tórelik etiwge jetisken kisi.  2. Hámeldiń túri, belgili bir aymaqqa basshılıq etiw ushın saylanıp qoyılǵan adam.", experience: "Shúrshit, qalmaq jetti páreń, Ákeń seniń Eset gereń, Bolıs bolsań adam jer eń. Abıray aqsaqal bolǵanıń (Berdaq)."},
    { word: "Aqsar", meaning: "at. Shóptiń túri, seksewilge uqsaǵan, tikensiz ósimlik, otqa jaǵıladı.", experience: "Dúysenbay Turımbetti qaptalına alıp, shetirektegi bir túp aqsardı ayaǵı menen pıshırlatıp ústine shókti (T.Qayıpbergenov)."},
    { word: "Aqsawlaq", meaning: "at. Qamırdan arnawlı túrde, júdá juqa etip pisirilgen nannıń túri. Aqsawlaq — qaraqalpaqtıń MILLIY awqatınıń biri, qawın aqsawlaq qawındı ábden qaynatıp, oǵan qatıq aralastırıp ishine aqsawlaqtı tuwrap, ústine sarı may kúydirip quyıp jelinedi, qawınsız tek qatıq penen de islenedi."},
    { word: "Aqsawıt", meaning: "at. Batırlardıń ústine (burınǵı waqıtlarda) oq ótpew ushın qorǵanıw ushın kiyip urısqa túsetuǵın kiyim, qabat-qabat temir setkadan toqılıp islengen urısta kiyetuǵın sırtqı úst kiyim.", experience: "Aqsawıt kiygen ústine, nayza alǵan dástine (Q.Maqsetov)."},
    { word: "Aq sálle", meaning: "at. Mollalardıń aq tawardan basına oraytuǵın bas kiyimi.", experience: "Aq sállesin tósektiń ústine shalqasına qoydı (K. Sultanov)."},
    { word: "Aq soqpaq", meaning: "at. Júre-júre joldıń shóp-sharınan tazarıp appaq (soqpaq) bolıwı, qayta-qayta tınbastan júrilip turatuǵın ayaq jol", experience: "Aq soqpaq penen bir-birine qaǵılısıp júrip kiyatırǵan malǵa deyin móńirep, olar da mazanı bermedi (A. Begimov)."},
    { word: "Aq suńqar", meaning: "at. Jabayı jırtqısh quslardıń tóresi.", experience: "Qatarınan artıq tuwǵan, Lashın aq suńqar yanlıdı (Ótesh)."},
    { word: "Aqsúyek", meaning: "at. Revolyuciyaǵa shekem xalıqlar ózlerin eki qatlamǵa bólip atap júrgen, solardıń joqarı qatlamın pristokratlar, aqsúyekler dep, al tómengi qatlamın (qarapayım xalıqlar) qara puqara delingen.", experience: "... kóteriliste geypara baylar, aqsúyekler qosılıp erkinlik alamız dep,... (S.Májitov)."},
    { word: "Aq súp", meaning: "at. Tawardıń túri, aq tawar, aq material."},
    { word: "Aq sút", meaning: "at. Ana súti, ulıwma sút.", experience: "Aq sút berip ósirdiń sen, Hesh te joq meniń ármanım (Á.Shamuratov)."},
    { word: "Aq tamaq", meaning: "kel. Juqa, páreni, júzinen kún kórinetuǵın kelinshek.", experience: "Shashı hasıl jupqa dodaq, Beli bir qısım aq tamaq, Uzın boylı hám keń qushaq, Peri kibi bolǵan eken (Berdaq)."},
    { word: "Aqtańlaq", meaning: "kel. Hár jerde aǵı bar.", experience: "Aqtańlaq kiyik tawda bar, Sáwirletip aydawda bar. Búgin tańda bir sawda bar, Jóndi soǵan burıp keldim (K.Irmanov)."},
    { word: "Aqtarıw", meaning: "f. Izlew, izlemegen jerdi qaldırmaw, qaraw, tintiw.", experience: "Policiya taw arasın, Aqtarıp júr onı quwıp(I.Yusupov)."},
    { word: "Aq terek", meaning: "at. Túri aq, dúp-dúziw, uzın, qurılıs materialları ushın paydalanılatuǵın aǵash.", experience: "Aq terek pe, kók terek, bizden sizge kim kerek (T.Mátmuratov)."},
    { word: "Aq úy", meaning: "at. Aq kiyiz, aq úzik penen jabılǵan qara úy.", experience: "...kiyatırǵan atlılar awıldan bólegirek tigilgen aq úyge qaray burıldı (qq.x. e.)."},
    { word: "Aqsha", meaning: "at. Pul, som.", experience: "Aydos onıń qorjınǵa salıp, atına bókterip qoyǵan aqshasın kórip, onı sheship almay, qanjar menen kesip aladı (qq.x. e.)."},
    { word: "Aqsham", meaning: "r. Tún, kesh, túngi waqıt, keshqurın.", experience: "Búgin aqshamı menen jawın jawdı. Tap usı máhálde «Alǵabasqa jawınnıń keregi az edi (Ó.Aytjanov)."},
    { word: "Aq shash", meaning: "at. Shashtıń aǵı, shashı aq, aǵarǵan shash.", experience: "Erman kiriw menen aq shash ananıń qolınan alıp stolǵa jaqın otırdı (S.Xojaniyazov)."},
    { word: "Aqshıl", meaning: "kel. Aqlaw, aqqa beyim, aq sur, aqlan.", experience: "Ájiniyazdıń aqshıl júziniń alması qızǵısh, gúreń tartıp, jawdıraǵan kóz janarı qubılıp ketti (K.Sultanov)."},
    { word: "Aqıbet", meaning: "at. Iz, soń, saldar, aqır, keyin.", experience: "Kewillerge qayǵı toldı, qayǵı tarqaǵay aqıbet (Berdaq)."},
    { word: "Aqıl", meaning: "at. Danalıq, bilim, bilgenlik, oy-sana.", experience: "Isenemen ilim menen aqılǵa, jer júzinde ájayıp is dóretken (Sh.Mámbetmuratov)."},
    { word: "Aqıl-sana", meaning: "at. Aqıl-oy, aqıl-dana.", experience: "Partiya ómirimiz, aqıl-sanamız... (X.Seytov)."},
    { word: "Aqılsız", meaning: "kel. Aqılı joq, bası islemeytuǵın, oysız, nadan.", experience: "Atasınan jaman bolsa, onı jaqsı dep kim aytar, aqılsız hám nadan bolsa, onı jaqsı dep kim aytar (Berdaq)."},
    { word: "Aqılsızlıq", meaning: "at. Aqmaqlıq, oysızlıq, kórgensizlik.", experience: "Bilgir sózin tıńlamaǵan, gáp mánisin ańlamaǵan. Úlkennen násiyat almaǵan, aqılsızlıq bolǵan eken (Berdaq)."},
    { word: "Aqım", meaning: "at. Okop., tereń shuqır, qorǵanıw ilaj, jasırınıw qorǵanıw, jasırın júriw jolı.", experience: "Ol zamannıń adamları jerden aqım qazıp, arbadan qamal etip, bir jerde jasırın júriw jolda úyilip otıratuǵın edi («Alpamıs»)."},
    { word: "Aqın", meaning: "at. Shayır, jazıwshı.", experience: "Zıyanı joq aytıssań men jeńermen, qazaqta Meńesh degen aqın qızban (Ájiniyaz)."},
    { word: "Aqıra", meaning: "at. Qazıwda shıǵarılǵan topıraq hám sol topıraqtıń túsken ornı.", experience: "Aqırası ılayǵa toldı (A.Bekimbetov)."},
    { word: "Aqıret", meaning: "at. 1. Azap, jábir, zulımlıq, qısıwmet. qorlıq, zorlıq, zombılıq. 2. din. Ol dúnya diniy kózqaras boyınsha adam ólgennen keyingi dúnya.", experience: "Arqalandıq arbanlap, Aqıret kórdik ólimnen (Jiyen jıraw). Aqırette keynine ereyin, Alla salsa ne islerdi kóreyin («Qırq qız»)."},
    { word: "Aqırzaman", meaning: "at. 1. din. Eski diniy ańızlarda aytılıwınsha, dúnyanıń sońı, izi, ayaǵı, tamam bolıwı, barlıq tirishiliktiń tawsılıwı. 2. Azap-aqıret, awırmanshılıq.", experience: "Aqır bir kún bolar aqırzamanı, Israpıl súrgini jıǵarlar tawdı (Ájiniyaz). Tústi basqa aqırzaman, inan, doslar, jalǵan emes (Berdaq). Hásen xan bes erdiń qanın almaqshı, Baslarına aqırzaman salmaqshı («Er Ziywar»)."},
    { word: "Aqırı", meaning: "r. Soń, keyin.", experience: "Azanda erte turıp jumısqa barıw kerek emes pe? Sol ushın kirpik ayqastırǵanday dem alıw zárúr, aqırı. (Ó.Xojaniyazov)."},
    { word: "Aq jaǵal", meaning: "Ala, ılaqtıń, qozınıń túrine qaray ataw, bas betinde meni bar.", experience: "Japıraq múyiz aq jaǵal, Ol da keldi suw betke (I.Yusupov)."},
    { word: "Aqıy", meaning: "Biy, sher, ózin joqarı sanaytuǵın adam.", experience: "Astında bar torı atı, Belinde gá har polatı, Bolıstıń quyrıq qanatı, Aqsaqalıń aqiy eken (Ájiniyaz)."},
    { word: "Aqkóz", meaning: "Gódek, ańqaw, hadal, hesh nárse kórmegen.", experience: "Munday awır aqkóz batırlardı sol zamandaǵı Xiywa xanı Ispandiyar xan óltirtken (Q.Irmanov)."},
    { word: "Aqsawlaq", meaning: "Qamırdan arnawlı túrde, júdá juqa etip pisirilgen nannıń túri."},
    { word: "Aq siyne", meaning: "Kóksi, kókirek awız, jalańash dene, tóstiń ústi.", experience: "Meniń ózim erke bolsam, Qız jamılǵan kórpe bolsam, Kórpedegi búrge bolsam, Aqsiyneńde jatpas pa edim (Berdaq)."},
    { word: "Aq tal", meaning: "Terektiń túri, túri aq, taza tikensiz, báhárde minár hámme tereklerden burın bórtedi.", experience: "Bálent hawalı aq tallar yanlı Kulen bolıs (Berdaq)."},
    { word: "Aq tiken", meaning: "Bozda ósetuǵın tikenekli shóp.", experience: "Qashqın lám-mim. Aq tikenliktiń arası sılt etpeydi. Tıp-tınısh. Bir shóp qıymıldamaydı (Ó.Xojaniyazov)."},
    { word: "Aqtuba", meaning: "Jerdiń, kóldiń atı, geografiyalıq atama.", experience: "Aqtubanıń aqqan suwı ılaydı, Eki diyqan ún salısıp jılaydı, Qazı iyshanǵa bizdi satqan qudaydı, Diyqan ashtan óler boldı Qazı iyshan («Qazı iyshan»)."},
    { word: "Aq shabaq", meaning: "Balıqtıń bir túri, maydaraq boladı.", experience: "Barıp kórse qazaǵa, aq shabaq penen aqsazan, sıyǵanınsha tolıptı (A.Dabılov)."},
    { word: "Ala awızlılıq", meaning: "at. Qarama-qarsılıq, awızbirshilik joqlıq, bir-birine isenbewshilik.", experience: "Bir awızlıq hár maqsetti boldırar, ala awızlıq orta jolda qaldırar. Ala bolǵan awızındaǵını aldırar, joldas bolsań bunnan xabarıń bolsın (K.Irmanov)."},
    { word: "Alabajaq", meaning: "kel. Shubar, hár túrli, túrli-túrli boyawı bar, ala shubar, ala bashaq, alabajıraq.", experience: "Bul kisi ústine alabajaq shapan kiygen (Aybek).... mına meniń dizemnen kelmeytuǵın alabajaq bir shapandı berdi (Q.Irmanov)."},
    { word: "Alabáhár", meaning: "r. Erte báhár, báhár máwsimi.", experience: "Eldiń ústine túsken awırmanlıq alabáhárden baslap jazı menen dawam etip atır (A.Begimov)."},
    { word: "Alaburkan", meaning: "kel. Alasapıran, qalay bolsa solay, tasıp tógiliw, shennen tıs burqasınlaw, kúyip-pisip tullanıw. shań, tas aralas uytqıǵan dawıl.", experience: "Alaburqan, ele teńiz tuwlaydı, tolqınlanıp kóbiklenip oynaydı (Á.Shamuratov)."},
    { word: "Alagewgim", meaning: "r. Erte, tań qarańǵısı, tań jańa aǵarıp kiyatırǵan waqıt.", experience: "Ótemurat alagewgimde ılashıǵınan maydanǵa shıqtı da dárya boyına qaray áste júrdi (K.Sultanov)."},
    { word: "Alagólek", meaning: "kel. Aq kewil, aq peyil, kishi peyil.", experience: "Ol bir alagólek jigit edi (Q.Ayımbetov)."},
    { word: "Alaǵada", meaning: "r. Tınıshsız, kewilsiz, bir nársege ǵalawıtlanǵan.", experience: "Jaslar oqıw ushın kelgen bul jerge, alaǵada salıp ǵalawıt berme! (I.Yusupov)."},
    { word: "Ala duman", meaning: "kel. Shańǵıt, dumanlıq, tútin. ", experience: "Ala duman átiraptan shań ushar, kúndiz túri jańa atqan tań usar ( T.Seytjanov)."},
    { word: "Ala kóz", meaning: "at. Kózi alalıq, úlken kóz.", experience: "Ala kózli Ernazardıń, sen dep ólgen balań edi (I.Yusupov)."},
    { word: "Alaqay", meaning: "t.s. Quwanısh, sezim.", experience: "Alaqay-alaqay, ya quday. Palman aǵam kiyatır (N.Dáwqaraev)."},
    { word: "Alaqan", meaning: "at. Qoldıń quwıslaytuǵın jeri, qoldıń ishki tárepi."},
    { word: "Alaman", meaning: "at. Xalıq, qalayıq, jurtshılıq, bir topar adamnıń úyiri, bir jerge kóp adamlardıń toplanıwı.", experience: "Ayımjamal alamannıń ishine súńgip ketti (Ó.Xojaniyazov)."},
    { word: "Ala moynaq", meaning: "kel. Qaraqalpaq saz ásbaplarınıń túri duwtarǵa aytıladı.", experience: "Keregeniń basında ildiriwli ala moynaq duwtardı aldı («Ámiwdárya» j.)."},
    { word: "Alap", meaning: "at. Keńislik, maydan, keń dala, dalalıq."},
    { word: "Ala sala", meaning: "r. Dárriw, birden.", experience: "Bir waqta Abıl jerde jatqan aybaltanı ala sala maǵan umtıldı (A.Bekimbetov)."},
    { word: "Alasar", meaning: "at. Qustıń atı.", experience: "Hawadan ushqan alasar, urıday kiriw qalaǵa, Surtayshaǵa miyasar («Qırq qız»)."},
    { word: "Alasat", meaning: "at. Ǵawǵa, shawqım, jánjel, alasapıran, waqıya, ózgeris.", experience: "At shaptırdı dalaǵa, jar urdırdı qalaǵa, qalaǵa jaw keldi dep, alasat urdı araǵa («Máspatsha»)."},
    { word: "Ala sáhár", meaning: "r. Erte, tań azan, tań qarańǵısı, tań atar-atpas waqıt.", experience: "Biybixatsha apay ala sáhárden turıp soǵan qarap jol tarttı (A.Begimov)."},
    { word: "Alaslaw", meaning: "f. gón.s. Eskishe emlewdiń bir túri.", experience: "Gúlimdi hám alasladı, kóp ırımdı etken eken (Berdaq)."},
    { word: "Alası", meaning: "at. Alatuǵın haqısı, alıw kerek zatı, haqı.", experience: "Onıń da kassirde alası haqı bar eken (A. Bekimbetov)."},
    { word: "Alasha", meaning: "at. Qoldan toqılǵan kishkene tósekshe, tósek ushın geyde kiyim shapan ushın da islenetuǵın material, júnnen de, paxta, jipekten de qádimgi tawarlardan qalıń etip toqıladı, kóbinese tósekke arnaladı, túrli boyawlarǵa jipti boyap toqıydı.", experience: "Astımızǵa tósediń, gilem emes alasha, qudashalar sóyleńiz, bir maydan bolsın tamasha (Q.Ayımbetov)."},
    { word: "Alba-dalba", meaning: "kel. Jaman, jırtıq, pájmúrde kiyingen, kiyim forması ájeptáwir.", experience: "Barsań, ústi bası alba-dalba bolıp, Gúlzar apasınıń qábiriniń basında eńirep otır (X.Seytov)."},
    { word: "Albıraqlaw", meaning: "f. Jol taba almaw, sasqalaqlaw, qısınıw.", experience: "Albıraqlap júrip esikti ashqanda mańlayıma ergenek tiyip, kóz aldım ottay jandı (J.Aymurzaev)."},
    { word: "Albıraw", meaning: "f. Qısınıw, qáweterleniw, kewilsizleniw, gúdikleniw, qolaysız jaǵdayǵa túsiw, jol tappaw.", experience: "Albıraǵan úyrek aldı menen de, artı menen de júzedi (qq.x.n.)."},
    { word: "Algebra", meaning: "at. Sanlardıń az-kópligine qaramay olardıń ulıwma nızamın úyretetuǵın matematikanıń tarawı.", experience: "Durıs, bir mártebe algebradan, bir mártebe rus tilinen úsh aldı (T.Qayıpbergenov)."},
    { word: "Alǵárez", meaning: "m.s. Sózdiń qısqası, toq eteri, juwmaǵı.", experience: "Alǵárez kórmedim bunıńday qızdı, xoshirey, xosh kewil, ashıq bir júzli (A.Begimov)."},
    { word: "Alǵır", meaning: "kel. Júyrik, ótkir, qıran, ziyrek, shaqqan.", experience: "Alǵır qustıń pánjesi, úsh qızınıń genjesi, Sarısha sulıw der edi (Q.Ayımbetov)."},
    { word: "Alǵıs", meaning: "at. Raxmet, táńir jarılqasın, ırzalıq.", experience: "Bul sózlerdi jazdı qolım, búlbúl yanlı sayrap tilim. Bul báyitti tıńlap elim, qanday alǵıs berer eken (Berdaq)."},
    { word: "Alǵısnama", meaning: "at. Úzliksiz miyneti ushın aytılǵan yamasa berilgen rásmiy húrmet belgisi.", experience: "Húkimet tárepinen berilgen rásmiy qutlıqlaw xatı."},
    { word: "Aldaǵı", meaning: "r. Aldınǵı qatardaǵı, ilgeridegi.", experience: "Maǵan bul birese quwanısh berse, qorqaman taǵı da aldaǵı joldan (M.Dáribaev)."},
    { word: "Aldanıw", meaning: "f. Birewlerden pánt jew, ótirikke isenip qalıw, ótirikke inanıw, qurı dalaǵa hálekleniw, isenimi joytılıw.", experience: "Sol waqıtta barıp Aytımbet aldanǵanın bilip jambasına bir urdı (Q.Ayımbetov)."},
    { word: "Aldaw", meaning: "f. 1. Ótirik aldap birewdi isendirip pánt beriw, ótirikke inandırıw, ótirik aytıw, ótirik sóylew.", experience: "Nadan tuwǵan Aydos biy, aldaw tilge inanıp, bir bále qılıp keler dep, jolın kútip júr edi (Berdaq)."},
    { word: "Aldın", meaning: "r. Birinshi, burın, áwel, dáslep, erterek bolıp ótken mánisinde.", experience: "Bárinen aldın, ocherk estetikalıq qural bolıw jaǵınan nasazlıq etti (G.Esemuratov)."},
    { word: "Aldına", meaning: "r. Ortaǵa, kópshilikke, hámmege.", experience: "Serimbet ornınan turıp, jıynalıstı ashtı hám kópshiliktiń aldına kún tártibin qoydı (Ó.Ayjanov)."},
    { word: "Aldınǵı", meaning: "kel. Ilgeri, áwelgi, dáslepki, aldaǵı, keyingi emes.", experience: "Aldınǵı arba qaydan júrse, sonǵı arba da sonnan júredi (qq.x.n.)."},
    { word: "Aljas", meaning: "f. Qátelesiw, jańılısıw."},
    { word: "Aljıǵan", meaning: "kel. Qátelesken, buzılǵan, aynıǵan, aljasqan, sózin buzǵan.... ", experience: "onıń hayalı: aljıǵan, kelindi qayda aparasań? dep baqırıp edi ... (Q.Ayımbetov)."},
    { word: "Aljıw", meaning: "f. Aqılınan, esinen ayırılıw, qartayıw, aljasıw, biymáni gáplerdi sóylew.", experience: "Hay, aljıǵan ǵarrı-aw, namazıńdı buzıp qoydıń ǵoy («Ámiwdárya» j.)."},
    { word: "Aliment", meaning: "(lat. alimentum qarawında, baǵıwında).", experience: "Nızamda belgilengen jaǵdayda shańaraqtıń bir aǵzası tárepinen basqa aǵzası yamasa aǵzaların qarjılay támiyinlew ushın májbúriy tólenetuǵın pul, napaqa."},
    { word: "Alif", meaning: "Arab álipbesiniń birinshi háribi hám ataması."},
    { word: "Alkash", meaning: "(rus. alkagolik sózinen) s.t. Ishkilikke berilgen, soǵan ósh bolǵan."},
    { word: "Alqım", meaning: "at. Moyın, gegirdek (iyek penen iyinniń aralıǵı)."},
    { word: "Alqımlaw", meaning: "f. Buwındırıw, alqımınan buwıw, alqımınan qısıw.", experience: "Eger urı baspashı jol tosıp jatsa, alqımdan buwǵanda bilmey qalasan (K.Sultanov)."},
    { word: "Alqıssa", meaning: "q.s. Sóz basında avtorlar tárepinen qollanılatuǵın kiris sóz, solay etip, qısqası, qullası.", experience: "Alqıssa burınǵı ótken zamanda Rus sháhárinde Arıslanbay degen bir bay bar edi («Góruǵlı»)."},
    { word: "Alla", meaning: "at. din. 18 mın álemdi, qıyamet-qayımdı jaratıwshı Quday, qúdiret iyesi, dúnyanıń payda bolıwında hám onıń ómir súriwinde qúdiretke iye."},
    { word: "Allahu akbar", meaning: "Arabsha alla ullı degen mánide."},
    { word: "Allegoriya", meaning: "(grek allegoria ózgeshe ańlatıw) kórkem ádebiyatta pikirdi tuwrı aytpay obrazlı túrde astarlap aytıw arqalı súwretlewdiń bir túri.", experience: "Erteklerdegi haywanlar, tımsallardaǵı qatnasıwshılar allegoriyalıq xarakterge iye."},
    { word: "Allergiya", meaning: "(grek allos-basqa+ergon-tásir) Organizmniń qorshaǵan átirapta ushıraytuǵın, allergenler dep atalıwshı geypara faktorlar (ximiyalıq zatlar, mikroblar hám olardıń turmıs sharayatında payda bolatuǵın ónimler, azıq-awqatlar) tásirinde (tiykar) júdá sezgir bolıwı."},
    { word: "Allo", meaning: "m. s. (ingl. hello) Telefon arqalı sóyleskende «esitip atırman» yamasa «esitip atırsız ba?» degen mánilerde qollanıladı."},
    { word: "Alma I", meaning: "at. Ráwshan gúlliler tuqımlasına kiretuǵın miyweli jemis aǵashı, terek, miyweniń túri.", experience: "Anaw turǵan almameken narmeken, sayasında jatqan biziń yarmeken (N.Dáwqaraev)."},
    { word: "Alma II", meaning: "f. Qoy, alıwǵa ruqsat joq, tiyme, qozǵama."},
    { word: "Almagezek", meaning: "r. Gezekpe-gezek, gezek penen, gezek boyınsha, reti menen, retpe-ret.", experience: "Qızlargúl menen birge almagezek bala kóterip esin biletuǵınlarǵa ertek aytıp otır edi (T.Qayıpbergenov)."},
    { word: "Almaz", meaning: "at. Taza kristall, uglerod. Oǵada kúshli qattılıǵı, bekkemligi menen ajıralıp turadı."},
    { word: "Almas", meaning: "at. Hasıl tas, gáwhar, bekkem."},
    { word: "Almurt", meaning: "at. Ráwshan gúlliler tuqımlasına kiretuǵın biyikligi 8-15 mm ge teń jemis aǵashı.", experience: "Fiolet qalqanları alma, almurt erikte jasaydı (A.Daljanov)."},
    { word: "Aloe", meaning: "(grek. aloe) Gernaylı yamasa qızǵaldaq tárizli tuqımlaslarına tiyisli, kóp suwlı hám japıraǵı qalıń tropikalıq hám subtropikalıq ósimlik."},
    { word: "Alp", meaning: "folk. Qaraqalpaq xalıq dástanlarında ǵayrı-tábiyǵıy kúsh-quwatı, mártligi, dáwjúrekligi t.b. menen ajıralıp turatuǵın qaharman.", experience: "Alp anadan tuwadı, at biyeden tuwadı (qq.x.n)."},
    { word: "Alpıs", meaning: "s. Alpıs birlikten turatuǵın san, 60 cifrı menen sanınıń ataması."},
    { word: "Alpıs tuwar", meaning: "at. Qızlardıń ata-anasına tólenetuǵın qalıń maldıń belgili muǵdarı, shaması, mólsheri.", experience: "Sóz alpıs tuwar beriwge shekem bardı (Q.Aralbaev)."},
    { word: "Altaqta", meaning: "at. Arbanıń aldı betinde arbakesh hám basqa da birli-yarım adamlar otırıw ushın arnalǵan orın. ", experience: "Onıń altaqtasına qızıl gilem, kókiregine quraq kórpesheler tóseliwde (T. Qayıpbergenov)."},
    { word: "Altaw", meaning: "s. Sanlıqtıń jıynaqlaw túri."},
    { word: "Altı", meaning: "s. Sanaq san, sanı altaw, esabı altaw."},
    { word: "Altın", meaning: "at. xim. Júdá qunlı, bahalı, jumsaq sarı túsli metall.", experience: "Arpa, biyday as eken, altın, gúmis tas eken. (qq.x.n.)"},
    { word: "Altın-valyuta", meaning: "at. ekon. Mámleketlik bank qarjı organlarında saqlanatuǵın altın hám shet ellik valyuta qorı."},
    { word: "Altınshı", meaning: "1. Kóbinese altınnan zergerlik buyımların jasaytuǵın usta, zerger. 2. Altın menen shuǵıllanatuǵın, satatuǵın satıwshı."},
    { word: "Alwan-alwan", meaning: "Túrli-túrli, hár qıylı."},
    { word: "Alsha", meaning: "at. Ráwshan gúlliler tuqımlasına kiretuǵın jemis aǵashı, terek."},
    { word: "Alıq", meaning: "Jawlasqan eki táreptiń jengen jeńilgeninen alınatuǵın mal-múlk, pul."},
    { word: "Alımsaq", meaning: "Tilenshi, alǵısh, esabın tawıp ala beretuǵın, alıwdı jaqsı kóretuǵın adam."},
    { word: "Alıpsatar", meaning: "at. ekon. Tayar ónimdi satıp alıp, ústine baha qoyıp, qımbat satatuǵın adam, sawdager."},
    { word: "Alıs I", meaning: "r. Uzaq, qashıq, shalǵay.", experience: "Awıl alıs jer shalǵay, jetalmadım jayawlap (Q.Ayımbetov)."},
    { word: "Alıs II", meaning: "f. Birge alıw, uslasıw, kóterisiw."},
    { word: "Alıs-beris", meaning: "at. Beris-alıs, qarım-qatnas."},
    { word: "Alıspaq", meaning: "at. Gúres, at ústinde gúresiw, bellesiw, oyın ataması.", experience: "Alıspaq kerek pe? shabıspaq kerek pe? tańla! shártim sol, dep tirenip turdı (gazetadan)."},
    { word: "Alıw I", meaning: "f. 1. Iyelew, mengeriw, iykemlew.  2. Boysındırıw, biylew.", experience: "Jańadan dokument alıp, baslawısh mektepke berdi balların (A.Dabılov)."},
    { word: "Alıw II", meaning: "at. mat. Arifmetikalıq ámel, sandı azaytıw ámeli.",},
    { word: "Alıwshı", meaning: "at. Zattı, nárseni alatuǵın adam, alajaq kisi."},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},

    
    { word: "Argotexnika", meaning: "at. Awıl xojalıq eginlerin islewdiń sisteması, diyqanshılıq hám olardı rawajlandırıw sharaları, ilajları.", experience: "Barlıq agrotexnika quralların keńnen qollanıw zárúr (O. Berdimuratov)."},
    { word: "Aǵzam", meaning: "Ullı mártebeli, ullı dárejeli", experience: "Quda qálese patsha aǵzam puqaralarına miyrimin salar (K.Sultanov)."},
    { word: "Aǵıl-tegil", meaning: "Molshılıq, mol-molaqay, kóp, dım kóp, jetkilikli.", experience: "Bunnan basqa da onıń sútli sıyırı bolıp, may menen sút aǵıl-tegil edi (S.Ayniy)."},
    
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    { word: "", meaning: "", experience: ""},
    // Bu yerda boshqa 1000 ta so‘zni qo‘shishingiz mumkin...
];

  function searchWord() {
    const searchTerm = document.getElementById("searchInput").value.toLowerCase();
    const filteredWords = words.filter(word => word.word.toLowerCase().includes(searchTerm));
    displayResults(filteredWords);
  }

  document.getElementById("searchInput").addEventListener("keydown", function (event) {
    if (event.key === "Enter") {
      searchWord();
    }
  });

  function displayResults(wordsList) {
    const resultsContainer = document.getElementById("resultsContainer");
    resultsContainer.innerHTML = "";

    if (wordsList.length === 0) {
      resultsContainer.innerHTML = "<p>Hesh qanday nátiyje tabılmadı.</p>";
      return;
    }

    wordsList.forEach(wordObj => {
      const wordCard = document.createElement("div");
      wordCard.classList.add("word-card");

      wordCard.innerHTML = `
        <div class="word-title">${wordObj.word}</div>
        <div class="word-details">
          <div class="meaning-box"><strong>Mánisi:</strong> ${wordObj.meaning}</div>
          <div class="example-box"><strong>Mısal:</strong> ${wordObj.experience}</div>
        </div>
      `;

      resultsContainer.appendChild(wordCard);
    });
  }
